package com.vekomy.vbooks.util;


import java.text.MessageFormat;
import java.text.NumberFormat;
import java.util.Locale;
import java.util.ResourceBundle;

/**
 * @author Satish
 *
 * 
 */
public class Msg {

	/**
	 * ResourceBundle variable holdes bundle.
	 */
	private static ResourceBundle bundle;

	static {
		loadResource();
	}

	/**
	 * load default US resource
	 */
	private static void loadResource() {
		bundle = ResourceBundle.getBundle("MessagesBundle", Locale.US);
		
	}

	/**
	 * load locale specific resource
	 * 
	 * @param locale
	 */
	public static void loadResource(Locale locale) {
		if (null == locale) {
			locale = Locale.US;
		}
		Locale.setDefault(locale);
		bundle = ResourceBundle.getBundle("MessagesBundle", locale);
	}

	/**
	 * Returns the resource string for specified key
	 * 
	 * @param key
	 * @return
	 */
	public static String get(MsgEnum key) {
		if (bundle == null){
			return key.toString();
		}
		
		String s=bundle.getString(key.toString());
		return s;
	}


	/**
	 * Returns the resource string for specified key with dynamic arguments
	 * 
	 * @param key
	 * @param args
	 * @return
	 */
	public static String get(MsgEnum key, Object[] args) {
		
		Object[] params = new String[args.length];
		
		for (int i = 0; i < params.length; i++) {
	   		if(args[i] instanceof Number) {
    			NumberFormat numFormat = NumberFormat.getInstance(Locale.getDefault());
    			params[i] = numFormat.format(args[i]).toString();
    		} else if(args[i] instanceof String) {
    			params[i] = args[i].toString();
    		}
		}
		
		if (bundle == null)
			return key.toString();
		
		String str = bundle.getString(key.toString());
		
		str = MessageFormat.format(str, params);
		return str;
	}

	
	// Keys declared as final to avoid multiple key instances across application
	public enum MsgEnum {
		// Login
		LOGIN_INVALID_CREDENTIALS,
		LOGIN_DISABLED_CREDENTIALS,
		WARNING_PASSWORD_COUNT_MESSAGE,
		DISABLED_USER_ERROR_MSG,
		DATE_LABEL,
		//EMPLOYEE LABELS
		EMPLOYEE_MANAGE_EMPLOYEE,
		EMPLOYEE_MANAGE_EMPLOYEE_ADD_EMPLOYEE,
		EMPLOYEE_MANAGE_EMPLOYEE_SEARCH_EMPLOYEE,
		EMPLOYEE_MANAGE_EMPLOYEE_IMPORT_EMPLOYEE,
    	
		  	EMPLOYEE_USERNAME,
			EMPLOYEE_PASSWORD,
			EMPLOYEE_FULL_NAME_LABEL,
			EMPLOYEE_FIRST_NAME_LABEL,
			EMPLOYEE_MIDDLE_NAME_LABEL,
			EMPLOYEE_LAST_NAME_LABEL,
			EMPLOYEE_GRANTED_DAYS_LABEL,
			EMPLOYEE_ADDRESS_TYPES,
			EMPLOYEE_GENDER_LABLE,
			EMPLOYEE_GENDER_MALE_LABLE,
			EMPLOYEE_GENDER_FEMALE_LABLE,
			EMPLOYEE_EID_LABLE,
			EMPLOYEE_EMPLOYEE_NO_LABEL,
			EMPLOYEE_EMPLOYEE_TYPE_LABEL,
			EMPLOYEE_EMPLOYEE_TYPES,
			ADDRESS_TYPE_LABEL,
			DEFAULT_VALUE,
			DESCRIPTION,
			DEFAULT_TYPES,
			EMPLOYEE_DEPARTMENT_LABLE,
			EMPLOYEE_SUBJECTS_LABEL,
			EMPLOYEE_FATHER_NAME_LABEL,
			EMPLOYEE_MOTHER_NAME_LABEL,
			EMPLOYEE_RESIDENCE_PHONE_LABEL,
			EMPLOYEE_PHONE_LABEL,
			EMPLOYEE_BLOOD_GROUP_LABEL,
			EMPLOYEE_RELIGION_LABEL,
			EMPLOYEE_PLACE_OF_BIRTH_LABEL,
			EMPLOYEE_NATIONALITY_LABEL,
			EMPLOYEE_CAST_LABEL,
			EMPLOYEE_RACE_LABEL,
			EMPLOYEE_ADDRESS_LANE1_LABEL,
			EMPLOYEE_ADDRESS_LANE2_LABEL,
			EMPLOYEE_LOCALITY_LABEL,
			EMPLOYEE_LAND_MARK_LABEL,
			EMPLOYEE_CITY_LABEL,
			EMPLOYEE_STATE_LABEL,
			EMPLOYEE_MOBILE,
			EMPLOYEE_ALTERNATE_MOBILE,
			EMPLOYEE_PIN_CODE_LABEL,
			EMPLOYEE_ADDRESS_TYPE_LABEL,
			EMPLOYEE_PASSPORT_NUMBER,
			EMPLOYEE_DIRECT_LINE,
			EMPLOYEE_BASIC_INFO_LABEL,
			EMPLOYEE_ADDITIONAL_INFO_LABEL,
			EMPLOYEE_ADDRESS_LABEL,
			EMPLOYEE_PREVIEW_LABEL,
			EMPLOYEE_LOGIN_VIEW_SNO,
			EMPLOYEE_DAY_BOOK_NOT_CLOSED,
			EMPLOYEE_HAS_CLOSING_BALANCE,
			EMPLOYEE_HAS_PRODUCTS_CLOSING,
			EMPLOYEE_HAS_REQUEST_PENDING,
			EMPLOYEE_HAS_CHANGE_REQUEST_PENDING,
			EMPLOYEE_LOGIN_VIEW_USER_NAME,
			EMPLOYEE_LOGIN_VIEW_LOGIN_TIME,
			ORGANIZATION_TAB,
			ORGANIZATION_SUPER_USER,
			WARNING_NO_ADDRESS_TYPES_CONFIGURED,
			//LABELS CUSTOMER
			CUSTOMER_FULL_NAME,
			CUSTOMER_NAME,
			CUSTOMER_BUSINESS_NAME,
			CUSTOMER_REGION,
			CUSTOMER_BUSINESS_NAMES,
			CUSTOMER_INVOICE_NAME,
			CUSTOMER_NUMBER,
			CUSTOMER_DETAILS_EMAIL,
			CUSTOMER_GENDER,
			CUSTOMER_GENDER_MALE_LABLE,
			CUSTOMER_GENDER_FEMALE_LABLE,
			CUSTOMER_DETAILS_CUSTOMER_ID,
			CUSTOMER_DETAILS_ADDRESS_LINE_1,
			CUSTOMER_DETAILS_ADDRESS_LINE_2,
			CUSTOMER_DETAILS_LOCALITY,
			CUSTOMER_DETAILS_LANDMARK,
			CUSTOMER_DETAILS_CITY,
			CUSTOMER_DETAILS_STATE,
			CUSTOMER_DETAILS_PINCODE,
			CUSTOMER_DETAILS_ADDRESS_TYPE,
			CUSTOMER_DETAILS_MOBILE,
			CUSTOMER_DETAILS_ALTERNATE_MOBILE,
			CUSTOMER_DETAILS_RESIDENCE_PHONE,
			CUSTOMER_INFO,
			CUSTOMER_BASIC_INFO_LABEL,
			CUSTOMER_ADDITIONAL_INFO_LABEL,
			CUSTOMER_PREVIEW_LABEL,
			CUSTOMER_CHANGE_REQUEST_TYPE,
			
			CUSTOMER_ID,
			CREDIT_LIMIT,
			CREDIT_OVERDUE_DAYS,
			CREATED_BY,
			CREATED_DATE,
			MODIFIED_BY,
			MODIFIED_DATE,
			CUSTOMER_CREDIT_LABEL,
			CREDIT_ID,
			VALIDATE_ALERT_NAME,
			VALIDATE_ALERT_NAME_SPACES,
			VALIDATE_ALERT_TYPE,
			//END OF CUSTOMER LABELS
			
			// PRODUCT LABEL
			PRODUCT_MANAGE_PRODUCT, 
			PRODUCT_MANAGE_PRODUCT_CUSTOMER_COST,
			PRODUCT_MANAGE_PRODUCT_ADD_PRODUCT, 
			PRODUCT_MANAGE_PRODUCT_SEARCH_PRODUCT, 
			PRODUCT_MANAGE_PRODUCT_IMPORT_PRODUCT,
			PRODUCT_MANAGE_PRODUCT_CUSTOMER_COST_ADD_PRODUCT,
			PRODUCT_MANAGE_PRODUCT_CUSTOMER_COST_SEARCH_PRODUCT,
			PRODUCT_MANAGE_PRODUCT_CUSTOMER_COST_IMPORT_PRODUCT,

			PRODUCT_PRODUCT_NAME_LABEL, 
			PRODUCT_CATEGORY_LABEL,
			PRODUCT_BRAND_LABEL,
			PRODUCT_MODEL_LABEL,
			PRODUCT_BATCH_NUMBER_LABEL, 
			PRODUCT_DESCRIPTION_LABEL,
			PRODUCT_COST_PER_QUANTITY_LABEL, 
			PRODUCT_AVAILABLE_QUANTITY_LABEL, 
			PRODUCT_ARRIVED_QUANTITY_LABEL,
			PRODUCT_WAREHOUSE_QUANTITY_LABEL,
			PRODUCT_TOTAL_QUANTITY_LABEL,
			PRODUCT_CREATED_BY_LABEL, 
			PRODUCT_CREATED_DATE_LABEL, 
			PRODUCT_MODIFIED_BY_LABEL, 
			PRODUCT_MODIFIED_DATE_LABEL,
			PRODUCT_BASIC_INFO_LABEL, 
			PRODUCT_ADDITIONAL_INFO_LABEL, 
			PRODUCT_PREVIEW_LABEL,
			PRODUCT_COST_LABEL,
			PRODUCT_CUSTOMER_NAME_LABEL,
			PRODUCT_ASSIGNED_BY_LABEL,
			PRODUCT_QUANTITY_LABEL,	
			PRODUCT_QUANTITY_TYPE_LABEL,
			PRODUCT_SALES_EXECUTIVE_LABEL,
			PRODUCT_CUSTOMER_COST,
			PRODUCT_SERIAL_NUMBER_LABEL,
			PRODUCT_ARRIVED_QUANTITY_DATE,
			
			//STOCK_RETURNS LABELS
			STOCK_RETURNS_BUSINESS_NAME_LABEL,
			STOCK_RETURNS_INVOICE_NAME_LABEL,
			STOCK_RETURNS_DATE_LABEL,
			SALES_EXECUTIVE_NAME_LABEL,
			SALES_CREATED_DATE_LABEL,
			SALES_OPENING_BALANCE_LABEL,
			SALES_CLOSING_BALANCE_LABEL,
			SALES_LABEL,
			//SALES_BOOK LABLES
			SALES_BOOK_SALES_NUMBER_LABLE,
			SALES_BOOK_SALES_EXECUTIVE_LABLE,
			SALES_BOOK_CREATED_DATE_LABLE,
			SALES_BOOK_ADVANCE_LABLE,
			SALES_BOOK_OPENING_BALANCE_LABLE,
			SALES_BOOK_CUSTOMER_TRANSACTIONS_LABLE,
			SALES_BOOK_SELF_ALLOWANCE_LABLE,
			SALES_BOOK_AMOUNT_TO_BANK_LABLE,
			SALES_BOOK_AMOUNT_TO_FACTORY_LABLE,
			SALES_BOOK_CLOSING_BALANCE_LABLE,
			SALES_BOOK_PRODUCT_NAME_LABLE,
			SALES_BOOK_PRODUCT_BATCH_LABLE,
			SALES_BOOK_QUANTITY_RECIEVED_LABLE,
			SALES_BOOK_QUANTITY_OPENING_BALANCE_LABLE,
			SALES_BOOK_QUANTITY_SOLD_LABLE,
			SALES_BOOK_QUANTITY_TO_FACTORY_LABLE,
			SALES_BOOK_QUANTITY_CLOSING_BALANCE_LABLE,
			SALES_BOOK_QUANTITY_LABLE,

			SALES_BOOK_SALES_BOOK_INFO_LABEL,
			SALES_BOOK_SALES_BOOK_CASH_LABEL,
			SALES_BOOK_SALES_BOOK_PRODUCT_LABEL,
			SALES_BOOK_PREVIEW_LABEL,
			
			SALES_BOOK_MANAGE_SALES_BOOK,
			SALES_BOOK_MANAGE_SALES_BOOK_ADD_SALES_BOOK,
			SALES_BOOK_MANAGE_SALES_BOOK_SEARCH_SALES_BOOK,
			SALES_BOOK_MANAGE_SALES_BOOK_IMPORT_SALES_BOOK,
			// Sales Returns Labels
			SALES_RETURNS_BUSINESS_NAME_LABEL,
			SALES_RETURNS_INVOICE_NAME_LABEL,
			SALES_RETURNS_PRODUCT_NAME_LABEL,
			SALES_RETURNS_BATCH_NUMBER_LABEL,
			SALES_RETURNS_RETURN_QUANTITY,
			SALES_RETURNS_COST,
			SALES_RETURNS_TOTAL_COST,
			SALES_RETURNS_CREATED_DATE,
			SALES_RETURNS_EXECUTIVE_NAME,
			SALES_RETURNS_LABEL,
			SALES_RETURNS_DAMAGED_LABEL,
			SALES_RETURNS_RESALABLE,
			SALES_RETURNS_IS_APPROVED,
			//Delivery Note Labels
			INVOICE_NUMBER_LABEL,
			DELIVERY_NOTE_INFO_LABEL,
			DELIVERY_NOTE_PAYMENT_LABEL,
			DELIVERY_NOTE_PREVIEW_LABEL,
			DELIVERY_NOTE_BUSINESS_NAME_LABEL,
			DELIVERY_NOTE_INVOICE_NAME_LABEL,
			DELIVERY_NOTE_INVOICE_DATE_LABEL,
			DELIVERY_NOTE_CUSTOMER_CREDIT_LABEL,
			DELIVERY_NOTE_CUSTOMER_ADVANCE_LABEL,
			DELIVERY_NOTE_PRODUCT_NAME_LABEL,
			DELIVERY_NOTE_PRODUCT_QUANTITY_LABEL,
			DELIVERY_NOTE_TOTAL_COST_LABEL,
			DELIVERY_NOTE_PRODUCT_COST_LABEL,
			DELIVERY_NOTE_BONUS_QUANTITY_LABEL,
			DELIVERY_NOTE_BONUS_REASON_LABEL,
			DELIVERY_NOTE_PRESENT_PAYABLE_LABEL,
			DELIVERY_NOTE_PRESENT_CREDIT_LABEL,
			DELIVERY_NOTE_PREVIOUS_CREDIT_LABEL,
			DELIVERY_NOTE_PRESENT_ADVANCE_LABEL,
			DELIVERY_NOTE_TOTAL_PAYABLE_LABEL,
			DELIVERY_NOTE_PRESENT_PAYMENT_LABEL,
			DELIVERY_NOTE_BALANCE_LABEL,
			DELIVERY_NOTE_PAYMENT_TYPE_LABEL,
			DELIVERY_NOTE_CREATED_DATE_LABEL,
			DELIVERY_NOTE_AVAILABLE_QUANTITY_LABEL,
			DELIVERY_NOTE_FOR_PAYMENTS_LABEL,
			DELIVERY_NOTE_PAYMENT_TYPES,
			DELIVERY_NOTE_INVOICE_NAME,			
			// Day Book Labels
			SERIAL_NUMBER_LABEL,
			DAY_BOOK_VALIDATE_BANK_NAME,
			CURRENT_DATE,
			DAY_BOOK_VALIDATE_BRANCH_NAME,
			DAY_BOOK_VALIDATE_CHEQUE_NO,
			DAY_BOOK_NO_LABEL,
			DAY_BOOK_VALIDATE_BANK_LOCATION,
			DAY_BOOK_VALIDATE_PRESENT_PAYMENT,
			DAY_BOOK_VALIDATE_VEHICLE_METER_READING,
			DAY_BOOK_ALLOWANCES_LABEL,
			DAY_BOOK_BASIC_INFO_LABEL,
			DAY_BOOK_AMOUNT_LABEL,
			DAY_BOOK_PRODUCTS_LABEL,
			DYA_BOOK_VEHICLE_DETAILS,
			DAY_BOOK_PREVIEW_LABEL,
			DAY_BOOK_CREATED_DATE_LABEL,
			DAY_BOOK_METER_READING_LABEL,

			DAY_BOOK_SALES_EXECUTIVE,
			DAY_BOOK_REASON_TO_DEALER_PARTY_EXPENSES,
			DAY_BOOK_REPORTING_MANAGER,
			DAY_BOOK_OPENING_BALANCE_LABEL,
			DAY_BOOK_EXECUTIVE_ALLOWANCES,
			DAY_BOOK_DRIVER_ALLOWANCES,
			DAY_BOOK_VEHICLE_FUEL_EXPENSES,
			DAY_BOOK_VEHICLE_METER_READING,
			DAY_BOOK_VEHICLE_MAINTENANCE_EXPENSES,
			DAY_BOOK_OFFLOADING_CHARGES,
			DAY_BOOK_DEALER_PARTY_EXPENCES,
			DAY_BOOK_MUNICIPAL_CITY_COUNCIL,
			DAY_BOOK_MISCELLANEOUS_EXPENSES,
			DAY_BOOK_REASON_TO_MISCELLANEOUS_EXPENSES,
			DAY_BOOK_TOTAL_ALLOWANCES,
			DAY_BOOK_CUSTOMER_TOTAL_PAYABLE,
			DAY_BOOK_CUSTOMER_TOTAL_RECEIVED,
			DAY_BOOK_CUSTOMER_TOTAL_CREDIT,
			DAY_BOOK_AMOUNT_TO_BANK,
			DAY_BOOK_REASON_TO_AMOUNT_TO_BANK,
			DAY_BOOK_AMOUNT_TO_FACTORY,
			DAY_BOOK_CLOSING_BALANCE,
			DAY_BOOK_VEHICLE_NO,
			DAY_BOOK_DRIVER_NAME,
			DAY_BOOKS_STARTING_READING,
			DAY_BOOK_ENDING_READING,
			DAY_BOOK_REMARKS,
			DAY_BOOK_IS_RETURN,
			DAY_BOOK_ALLOWANCES_AMOUNT,

			DAY_BOOK_PRODUCT_NAME,
			DAY_BOOK_OPENING_STOCK,
			DAY_BOOK_PRODUCTS_TO_CUSTOMER,
			DAY_BOOK_PRODUCTS_TO_FACTORY,
			DAY_BOOK_CLOSING_STOCK,
			DAY_BOOK_BATCH_NUMBER,
			DAY_BOOK_RETURN_QUANTITY,
			DAY_BOOK_EXECUTIVE_ALLOWANCES_POP,
			DAY_BOOK_VEHICLE_NO_LENGTH,
			DAY_BOOK_AMOUNT_TO_FACTORY_POP,
			DAY_BOOK_SUM_POP,
			DAY_BOOK_AMOUNT_TO_BANK_POP,
			DAY_BOOK_VALIDATE_PAYMENT_TYPE,
			
			// Change Transaction Request Labels
			TRANSACTION_CHANGE_REQUEST_TYPE,
			TRANSACTION_CHANGE_REQUEST_DATE,
			
			//Accounts Labels
			ACCOUNTS_START_DATE,
			ACCOUNTS_DATE_LABEL,
			ACCOUNTS_SALES_EXECUTIVE_LABEL,
			ACCOUNTS_ADVANCE_LABEL,
			ACCOUNTS_PERVIOUS_CLOSING_BALANCE_LABEL,
			ACCOUNTS_CLOSING_BALANCE_LABEL,
			ACCOUNTS_OPENING_BALANCE_LABEL,
			ACCOUNTS_PRODUCT_NAME_LABEL,
			ACCOUNTS_AVAILABLE_QUANTITY_LABEL,
			ACCOUNTS_ALLOTMENT_LABEL,
			ACCOUNTS_PREVIOUS_CLOSING_STOCK_LABEL,
			ACCOUNTS_CLOSING_STOCK_LABEL,
			ACCOUNTS_OPENING_STOCK_LABEL,
			ACCOUNTS_REMARKS_LABEL,
			ACCOUNTS_RETURN_QTY,
			ACCOUNTS_BATCH_NUMBER_LABEL,
			ACCOUNT_ALLOTMENT_TYPE_LABEL,
			//#Organization Labels
			ORGANIZATION_SUB_BRANCH_ENABLED_ERROR,
			ORGANIZATION_MAIN_BRANCH_LABEL,
			ORGANIZATION_MAIN_BRANCH_TYPE_LABEL,
			ORGANIZATION_MAIN_BRANCH_NAME_LABEL,
			ORGANIZATION_ORGANIZATION_CODE_LABEL,
			ORGANIZATION_ORGANIZATION_NAME_LABEL,
			ORGANIZATION_BRANCH_NAME_LABEL,
			ORGANIZATION_DESCRIPTION_LABEL,
			ORGANIZATION_EMAIL_LABEL,
			ORGANIZATION_ADDRESS_LINE_1_LABEL,
			ORGANIZATION_ADDRESS_LINE_2_LABEL,
			ORGANIZATION_LOCALITY_LABEL,
			ORGANIZATION_LANDMARK_LABEL,
			ORGANIZATION_CITY_LABEL,
			ORGANIZATION_STATE_LABEL,
			ORGANIZATION_COUNTRY_LABEL,
			ORGANIZATION_ZIPCODE_LABEL,
			ORGANIZATION_CURRENCY_FORMAT_LABEL,
			ORGANIZATION_PHONE1_LABEL,
			ORGANIZATION_PHONE2_LABEL,
			ORGANIZATION_PHONE3_LABEL,
			ORGANIZATION_FULL_NAME_LABEL,
			ORGANIZATION_USERNAME_PREFIX_LABEL,
			ORGANIZATION_SUPER_USER_NAME_LABEL,
			ORGANIZATION_PASSWORD_LABEL,
			ORGANIZATION_LABEL,
			MANAGE_USER_USERNAME,
			MANAGE_USER_PWD,
			MANAGE_USER_FIRST_NAME,
			MANAGE_USER_DB_FIRST_NAME,
			MANAGE_USER_MIDDLE_NAME,
			MANAGE_USER_DB_MIDDLE_NAME,
			MANAGE_USER_EMAIL,
			MANAGE_USER_DB_EMAIL,
			MANAGE_USER_LAST_NAME,
			MANAGE_USER_DB_LAST_NAME,
			MANAGE_USER_ADDRESS_LINE1,
			MANAGE_USER_DB_ADDRESS_LINE1,
			MANAGE_USER_ADDRESS_LINE2,
			MANAGE_USER_LOCALITY,
			MANAGE_USER_DB_LOCALITY,
			MANAGE_USER_LAND_MARK,
			MANAGE_USER_DB_LANDMARK,
			MANAGE_USER_BLOOD_GROUP,
			MANAGE_USER_DB_BLOOD_GROUP,
			MANAGE_USER_PASSPORT_NUMBER,
			MANAGE_USER_DB_PASSPORT_NUMBER,
			MANAGE_USER_NATIONALITY,
			MANAGE_USER_DB_NATIONALITY,
			MANAGE_USER_CITY,
			MANAGE_USER_DB_CITY,
			MANAGE_USER_STATE,
			MANAGE_USER_DB_STATE,
			MANAGE_USER_ZIPCODE,
			MANAGE_USER_ADDRESS_TYPE,
			MANAGE_USER_MOBILE,
			MANAGE_USER_DB_MOBILE,
			MANAGE_USER_ORGANIZATION ,
			//Reports Labels
			REPORT_START_DATE_LABEL,
			REPORT_END_DATE_LABEL,
			REPORT_TYPE_LABEL,
			REPORT_CR_STATUS_LABEL,
			REPORT_RESALABLE_QTY_LABEL,
			REPORT_DAMAGED_QTY_LABEL,
			REPORT_ALLOWANCE_TYPE_LABEL,
			//Journals Labels
			JOURNAL_INVOICE_NO,
			JOURNAL_TYPE,
			JOURNAL_TYPES,
			JOURNAL_CREATED_DATE,
			JOURNAL_AMOUNT,
			CHANGE_REQUEST_DESCRIPTION,
			//VALIDATING CUSTOMER
			VALIDATE_CUSTOMER_BUSINESS_NAME,
			BUSINESS_NAME_NOT_AVAILABLE,
			SALES_EXECUTIVE_NAME_NOT_AVAILABLE,
			VALIDATE_BUSINESS_NAME,
			BUSINESS_NAME_VALIDATION,
			VALIDATE_INVOICE_NAME,
			INVOICE_NAME_VALIDATION,
			VALIDATE_CUSTOMER_NAME,
			CUSTOMER_NAME_VALIDATION,
			VALIDATE_MOBILE,
			VALIDATE_MOBILE_NUMBER,
			VALIDATE_EMAIL,
			VALIDATE_MAIL,
			VALIDATE_CREDIT_LIMIT,
			VALIDATE_ALTERNATE_MOBILE,
			VALIDATE_CREDIT_LIMIT_CHAR,
			VALIDATE_CREDIT_OVER_DUE_DAYS,
			VALIDATE_CRESIT_OVER_DUE_DAYS_CHAR,
			VALIDATE_DIRECT_LINE,
			VALIDATE_DIRECT_LINE_CHAR,
			VALIDATE_ALTERNATE_MOBILE_CHAR,
			VALIDATE_ADDRESS1,
			VALIDATE_ADDRESS1_CHAR,
			VALIDATE_ADDRESS2,
			VALIDATE_LOCALITY,
			VALIDATE_LOCALITY_CHAR,
			VALIDATE_LANDMARK,
			VALIDATE_LANDMARK_CHAR,
			VALIDATE_REGION,
			VALIDATE_REGION_CHAR,
			VALIDATE_STATE,
			VALIDATE_STATE_CHAR,
			VALIDATE_CITY,
			VALIDATE_CITY_CHARS,
			VALIDATE_ZIPCODE,
			VALIDATE_ZIPCODE_CHARS ,
			
			// Alerts ---> START
			//Alerts Labels
			ALERT_NAME_LABEL,
			ALERT_CATEGORY,
			ALERT_TYPE_LABEL,
			ALERT_DESCRIPTION_LABEL,
			ALERT_NOTIFICATION_LABEL,
			ALERT_USERS_LABEL,
			ALERT_EMAIL_NOTIFICATION_LABEL,
			ALERT_SMS_NOTIFICATION_LABEL,
			ALERT_GROUP_LABEL,
			ALERT_IN_SYSTEM_NOTIFICATION_LABEL,
			ALERT_CRITERIA_LABEL,
			ALERT_COUNT_LABEL,
			ALERT_ENABLE_DISABLE_LABLE,
			ALERT_START_DATE_LABEL,
			ALERT_END_DATE_LABEL,
			ALERT_SERIAL_NO,
			ALERT_CREATED_USER,
			ALERT_CREATED_DATE_LABEL,
			
			//Alerts Mailing Messages.
			ALERT_TYPE_WRONG_PWD_ENTRY_MESSAGE,
			ALERT_TYPE_SYSTEM_DEFAULTS_MESSAGE,
			ALERT_TYPE_STOCK_ALLOTMENT_MESSAGE,
			ALERT_TYPE_DAY_BOOK_CLOSURE_MESSAGE,
			ALERT_TYPE_ALLOWANCE_OVER_LIMIT_MESSAGE,
			ALERT_TYPE_CREDIT_OVERDUE_MESSAGE,
			ALERT_TYPE_JOURNAL_RAISED_MESSAGE,
			ALERT_TYPE_JOURNAL_DECLINED_MESSAGE,
			ALERT_TYPE_JOURNAL_APPROVED_MESSAGE,
			ALERT_TYPE_SALES_RETURN_RAISED_MESSAGE,
			ALERT_TYPE_SALES_RETURN_APPROVED_MESSAGE,
			ALERT_TYPE_SALES_RETURN_DECLINED_MESSAGE,
			ALERT_TYPE_CUSTOMER_CHANGE_REQUEST_RAISED_MESSAGE,
			ALERT_TYPE_CUSTOMER_CHANGE_REQUEST_APPROVED_MESSAGE,
			ALERT_TYPE_DELIVERY_NOTE_CHANGE_REQUEST_RAISED_MESSAGE,
			ALERT_TYPE_DELIVERY_NOTE_CHANGE_REQUEST_APPROVED_MESSAGE,
			ALERT_TYPE_DELIVERY_NOTE_CHANGE_REQUEST_DECLINED_MESSAGE,
			ALERT_TYPE_SALES_RETURNS_CHANGE_REQUEST_RAISED_MESSAGE,
			ALERT_TYPE_SALES_RETURNS_CHANGE_REQUEST_APPROVED_MESSAGE,
			ALERT_TYPE_SALES_RETURNS_CHANGE_REQUEST_DECLINED_MESSAGE,
			ALERT_TYPE_JOURNAL_CHANGE_REQUEST_RAISED_MESSAGE,
			ALERT_TYPE_JOURNAL_CHANGE_REQUEST_APPROVED_MESSAGE,
			ALERT_TYPE_JOURNAL_CHANGE_REQUEST_DECLINED_MESSAGE,
			ALERT_TYPE_DAY_BOOK_CHANGE_REQUEST_RAISED_MESSAGE,
			ALERT_TYPE_DAY_BOOK_CHANGE_REQUEST_APPROVED_MESSAGE,
			ALERT_TYPE_DAY_BOOK_CHANGE_REQUEST_DECLINED_MESSAGE,
			ALERT_TYPE_EXCESS_AMOUNT_MESSAGE,
			ALERT_TYPE_TRENDING_PRODUCT_PERCENTAGE_LESS_MESSAGE,
			ALERT_TYPE_TRENDING_AMOUNT_PERCENTAGE_LESS_MESSAGE,
			ALERT_TYPE_TRENDING_PRODUCT_PERCENTAGE_HIGH_MESSAGE,
			ALERT_TYPE_TRENDING_AMOUNT_PERCENTAGE_HIGH_MESSAGE,
			ALERT_TYPE_DAY_BOOK_HAVING_CLOSING_STOCK_MESSAGE,
			// Alerts ---> END
			
			// Exception Messages ---> START
			PERSISTING_SUCCESS_MESSAGE,
			PERSISTING_FAILURE_MESSAGE,
			RESULT_FAILURE_MESSAGE,
			RESULT_DISABLE_FAILURE,
			RESULT_SUCCESS_MESSAGE,
			DELETE_SUCCESS_MESSAGE,
			DELETE_FAILURE_MESSAGE,
			UPDATE_SUCCESS_MESSAGE,
			UPDATE_FAILURE_MESSAGE,
			BUSINESS_NAME_AVAILABILITY_RESULT_MESSAGE,
			PRODUCTS_NOT_CONFIGURED_MESSAGE,
			EMPLOYEE_NUMBER_GENERATION_FAILURE_MESSAGE,
			CANCELED_SUCCESS_MESSAGE,
			LOGIN_DISABLED_SUCCESS_MESSAGE,
			APPROVE_JOURNAL_MESSAGE,
			DECLINE_JOURNAL_MESSAGE,
			ASSIGN_CUSTOMERS_VALIDATION_FAILURE_MESSAGE,
			ASSIGN_CUSTOMERS_BUSINESS_NAME_EXISTS_MESSAGE,
			ASSIGN_CUSTOMERS_BUSINESS_NAME_NOT_EXISTS_MESSAGE,
			REMOVE_DATA_FROM_SESSION_MESSAGE,
			SECURITY_FAILURE_MESSAGE,
			ENCODE_FAILURE_MESSAGE,
			DECODE_FAILURE_MESSAGE,
			ASSIGN_CUSTOMER_PERSIST_FAILURE_MESSAGE,
			UPLOAD_FAILURE_MESSAGE,
			NO_SUCH_DIRECTORY_MESSAGE,
			DIRECTORY_CREATE_MESSAGE,
			DIRECTORY_CREATION_FAIL_MESSAGE,
			DOCUMENT_DELETE_SUCCESS_MESSAGE,
			DOCUMENT_DELETE_FAILURE_MESSAGE,
			CANCEL_SUCCESS_MESSAGE,
			CANCEL_BUTTON_MESSAGE,
			CLEAR_BUTTON_MESSAGE,
			// Exception Messages ---> END
			
			//System Look up messages ------>START
			INVOICE_NO_PERIOD,
			//System Look up messages ------> END
			
			// ACTIVEMQ
			ACTIVEMQ_IP,
			ACTIVEMQ_PORT,
			ACTIVE_QUEUE_NAME,
			ACTIVEMQ_BROKER_URL,
			ACTIVEMQ_INACTIVE_MESSAGE,
			ACTIVEMQ_TRANSPORT_INTERRUPTED_MESSAGE,
			ACTIVEMQ_TRANSPORT_RESUMED_MESSAGE,
			ACTIVEMQ_FEED_READING_FAILURE_MESSAGE,
			ACTIVEMQ_FEED_DELETE_FAILURE_MESSAGE,
	}
}