package com.vekomy.vbooks.hibernate.model;

// Generated Nov 19, 2013 10:32:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VbAlertTypeMySales generated by hbm2java
 */
public class VbAlertTypeMySales implements java.io.Serializable {

	private Integer id;
	private VbAlertType vbAlertType;
	private String alertMySales;
	private Set<VbAlertTypeMySalesPage> vbAlertTypeMySalesPages = new HashSet<VbAlertTypeMySalesPage>(
			0);
	private Set<VbMySales> vbMySaleses = new HashSet<VbMySales>(0);

	public VbAlertTypeMySales() {
	}

	public VbAlertTypeMySales(VbAlertType vbAlertType, String alertMySales) {
		this.vbAlertType = vbAlertType;
		this.alertMySales = alertMySales;
	}

	public VbAlertTypeMySales(VbAlertType vbAlertType, String alertMySales,
			Set<VbAlertTypeMySalesPage> vbAlertTypeMySalesPages,
			Set<VbMySales> vbMySaleses) {
		this.vbAlertType = vbAlertType;
		this.alertMySales = alertMySales;
		this.vbAlertTypeMySalesPages = vbAlertTypeMySalesPages;
		this.vbMySaleses = vbMySaleses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbAlertType getVbAlertType() {
		return this.vbAlertType;
	}

	public void setVbAlertType(VbAlertType vbAlertType) {
		this.vbAlertType = vbAlertType;
	}

	public String getAlertMySales() {
		return this.alertMySales;
	}

	public void setAlertMySales(String alertMySales) {
		this.alertMySales = alertMySales;
	}

	public Set<VbAlertTypeMySalesPage> getVbAlertTypeMySalesPages() {
		return this.vbAlertTypeMySalesPages;
	}

	public void setVbAlertTypeMySalesPages(
			Set<VbAlertTypeMySalesPage> vbAlertTypeMySalesPages) {
		this.vbAlertTypeMySalesPages = vbAlertTypeMySalesPages;
	}

	public Set<VbMySales> getVbMySaleses() {
		return this.vbMySaleses;
	}

	public void setVbMySaleses(Set<VbMySales> vbMySaleses) {
		this.vbMySaleses = vbMySaleses;
	}

}
