package com.vekomy.vbooks.hibernate.model;

// Generated Nov 19, 2013 10:32:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VbAlertCategory generated by hbm2java
 */
public class VbAlertCategory implements java.io.Serializable {

	private Integer id;
	private String alertCategory;
	private Set<VbAlertType> vbAlertTypes = new HashSet<VbAlertType>(0);

	public VbAlertCategory() {
	}

	public VbAlertCategory(String alertCategory) {
		this.alertCategory = alertCategory;
	}

	public VbAlertCategory(String alertCategory, Set<VbAlertType> vbAlertTypes) {
		this.alertCategory = alertCategory;
		this.vbAlertTypes = vbAlertTypes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAlertCategory() {
		return this.alertCategory;
	}

	public void setAlertCategory(String alertCategory) {
		this.alertCategory = alertCategory;
	}

	public Set<VbAlertType> getVbAlertTypes() {
		return this.vbAlertTypes;
	}

	public void setVbAlertTypes(Set<VbAlertType> vbAlertTypes) {
		this.vbAlertTypes = vbAlertTypes;
	}

}
