package com.vekomy.vbooks.hibernate.model;

// Generated Nov 19, 2013 10:32:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VbAlertType generated by hbm2java
 */
public class VbAlertType implements java.io.Serializable {

	private Integer id;
	private VbAlertCategory vbAlertCategory;
	private String alertType;
	private Set<VbUserDefinedAlerts> vbUserDefinedAlertses = new HashSet<VbUserDefinedAlerts>(
			0);
	private Set<VbAlertTypeMySales> vbAlertTypeMySaleses = new HashSet<VbAlertTypeMySales>(
			0);
	private Set<VbSystemAlerts> vbSystemAlertses = new HashSet<VbSystemAlerts>(
			0);

	public VbAlertType() {
	}

	public VbAlertType(VbAlertCategory vbAlertCategory, String alertType) {
		this.vbAlertCategory = vbAlertCategory;
		this.alertType = alertType;
	}

	public VbAlertType(VbAlertCategory vbAlertCategory, String alertType,
			Set<VbUserDefinedAlerts> vbUserDefinedAlertses,
			Set<VbAlertTypeMySales> vbAlertTypeMySaleses,
			Set<VbSystemAlerts> vbSystemAlertses) {
		this.vbAlertCategory = vbAlertCategory;
		this.alertType = alertType;
		this.vbUserDefinedAlertses = vbUserDefinedAlertses;
		this.vbAlertTypeMySaleses = vbAlertTypeMySaleses;
		this.vbSystemAlertses = vbSystemAlertses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbAlertCategory getVbAlertCategory() {
		return this.vbAlertCategory;
	}

	public void setVbAlertCategory(VbAlertCategory vbAlertCategory) {
		this.vbAlertCategory = vbAlertCategory;
	}

	public String getAlertType() {
		return this.alertType;
	}

	public void setAlertType(String alertType) {
		this.alertType = alertType;
	}

	public Set<VbUserDefinedAlerts> getVbUserDefinedAlertses() {
		return this.vbUserDefinedAlertses;
	}

	public void setVbUserDefinedAlertses(
			Set<VbUserDefinedAlerts> vbUserDefinedAlertses) {
		this.vbUserDefinedAlertses = vbUserDefinedAlertses;
	}

	public Set<VbAlertTypeMySales> getVbAlertTypeMySaleses() {
		return this.vbAlertTypeMySaleses;
	}

	public void setVbAlertTypeMySaleses(
			Set<VbAlertTypeMySales> vbAlertTypeMySaleses) {
		this.vbAlertTypeMySaleses = vbAlertTypeMySaleses;
	}

	public Set<VbSystemAlerts> getVbSystemAlertses() {
		return this.vbSystemAlertses;
	}

	public void setVbSystemAlertses(Set<VbSystemAlerts> vbSystemAlertses) {
		this.vbSystemAlertses = vbSystemAlertses;
	}

}
