package com.vekomy.vbooks.hibernate.model;

// Generated Nov 19, 2013 10:32:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VbCashDayBookCr generated by hbm2java
 */
public class VbCashDayBookCr implements java.io.Serializable {

	private Integer id;
	private VbSalesBook vbSalesBook;
	private VbOrganization vbOrganization;
	private VbCashDayBook vbCashDayBook;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private String dayBookType;
	private String valueOne;
	private String valueTwo;
	private String valueThree;

	public VbCashDayBookCr() {
	}

	public VbCashDayBookCr(VbSalesBook vbSalesBook,
			VbOrganization vbOrganization, VbCashDayBook vbCashDayBook,
			Date modifiedOn, String dayBookType) {
		this.vbSalesBook = vbSalesBook;
		this.vbOrganization = vbOrganization;
		this.vbCashDayBook = vbCashDayBook;
		this.modifiedOn = modifiedOn;
		this.dayBookType = dayBookType;
	}

	public VbCashDayBookCr(VbSalesBook vbSalesBook,
			VbOrganization vbOrganization, VbCashDayBook vbCashDayBook,
			Date createdOn, String createdBy, Date modifiedOn,
			String modifiedBy, String dayBookType, String valueOne,
			String valueTwo, String valueThree) {
		this.vbSalesBook = vbSalesBook;
		this.vbOrganization = vbOrganization;
		this.vbCashDayBook = vbCashDayBook;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.dayBookType = dayBookType;
		this.valueOne = valueOne;
		this.valueTwo = valueTwo;
		this.valueThree = valueThree;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbSalesBook getVbSalesBook() {
		return this.vbSalesBook;
	}

	public void setVbSalesBook(VbSalesBook vbSalesBook) {
		this.vbSalesBook = vbSalesBook;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public VbCashDayBook getVbCashDayBook() {
		return this.vbCashDayBook;
	}

	public void setVbCashDayBook(VbCashDayBook vbCashDayBook) {
		this.vbCashDayBook = vbCashDayBook;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getDayBookType() {
		return this.dayBookType;
	}

	public void setDayBookType(String dayBookType) {
		this.dayBookType = dayBookType;
	}

	public String getValueOne() {
		return this.valueOne;
	}

	public void setValueOne(String valueOne) {
		this.valueOne = valueOne;
	}

	public String getValueTwo() {
		return this.valueTwo;
	}

	public void setValueTwo(String valueTwo) {
		this.valueTwo = valueTwo;
	}

	public String getValueThree() {
		return this.valueThree;
	}

	public void setValueThree(String valueThree) {
		this.valueThree = valueThree;
	}

}
