package com.vekomy.vbooks.hibernate.model;

// Generated Nov 19, 2013 10:32:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbCustomerDetail generated by hbm2java
 */
public class VbCustomerDetail implements java.io.Serializable {

	private Integer id;
	private VbCustomer vbCustomer;
	private String addressLine1;
	private String addressLine2;
	private String region;
	private String locality;
	private String landmark;
	private String city;
	private String state;
	private String zipcode;
	private String mobile;
	private String alternateMobile;
	private String directLine;
	private String email;

	public VbCustomerDetail() {
	}

	public VbCustomerDetail(VbCustomer vbCustomer, String region,
			String locality, String mobile, String email) {
		this.vbCustomer = vbCustomer;
		this.region = region;
		this.locality = locality;
		this.mobile = mobile;
		this.email = email;
	}

	public VbCustomerDetail(VbCustomer vbCustomer, String addressLine1,
			String addressLine2, String region, String locality,
			String landmark, String city, String state, String zipcode,
			String mobile, String alternateMobile, String directLine,
			String email) {
		this.vbCustomer = vbCustomer;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.region = region;
		this.locality = locality;
		this.landmark = landmark;
		this.city = city;
		this.state = state;
		this.zipcode = zipcode;
		this.mobile = mobile;
		this.alternateMobile = alternateMobile;
		this.directLine = directLine;
		this.email = email;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbCustomer getVbCustomer() {
		return this.vbCustomer;
	}

	public void setVbCustomer(VbCustomer vbCustomer) {
		this.vbCustomer = vbCustomer;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getRegion() {
		return this.region;
	}

	public void setRegion(String region) {
		this.region = region;
	}

	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	public String getLandmark() {
		return this.landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getAlternateMobile() {
		return this.alternateMobile;
	}

	public void setAlternateMobile(String alternateMobile) {
		this.alternateMobile = alternateMobile;
	}

	public String getDirectLine() {
		return this.directLine;
	}

	public void setDirectLine(String directLine) {
		this.directLine = directLine;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

}
