package com.vekomy.vbooks.hibernate.model;

// Generated Jul 16, 2013 11:21:50 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VbDayBookChangeRequest generated by hbm2java
 */
public class VbDayBookChangeRequest implements java.io.Serializable {

	private Integer id;
	private VbSalesBook vbSalesBook;
	private VbOrganization vbOrganization;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private String salesExecutive;
	private Boolean isReturn;
	private String status;
	private String driverName;
	private String vehicleNo;
	private String startingReading;
	private String endingReading;
	private String remarks;
	private String crDescription;
	private Set vbDayBookChangeRequestAmounts = new HashSet(0);
	private Set vbDayBookChangeRequestProductses = new HashSet(0);

	public VbDayBookChangeRequest() {
	}

	public VbDayBookChangeRequest(VbSalesBook vbSalesBook,
			VbOrganization vbOrganization, Date modifiedOn,
			String salesExecutive, String vehicleNo, String startingReading,
			String endingReading) {
		this.vbSalesBook = vbSalesBook;
		this.vbOrganization = vbOrganization;
		this.modifiedOn = modifiedOn;
		this.salesExecutive = salesExecutive;
		this.vehicleNo = vehicleNo;
		this.startingReading = startingReading;
		this.endingReading = endingReading;
	}

	public VbDayBookChangeRequest(VbSalesBook vbSalesBook,
			VbOrganization vbOrganization, Date createdOn, String createdBy,
			Date modifiedOn, String modifiedBy, String salesExecutive,
			Boolean isReturn, String status, String driverName,
			String vehicleNo, String startingReading, String endingReading,
			String remarks, String crDescription,
			Set vbDayBookChangeRequestAmounts,
			Set vbDayBookChangeRequestProductses) {
		this.vbSalesBook = vbSalesBook;
		this.vbOrganization = vbOrganization;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.salesExecutive = salesExecutive;
		this.isReturn = isReturn;
		this.status = status;
		this.driverName = driverName;
		this.vehicleNo = vehicleNo;
		this.startingReading = startingReading;
		this.endingReading = endingReading;
		this.remarks = remarks;
		this.crDescription = crDescription;
		this.vbDayBookChangeRequestAmounts = vbDayBookChangeRequestAmounts;
		this.vbDayBookChangeRequestProductses = vbDayBookChangeRequestProductses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbSalesBook getVbSalesBook() {
		return this.vbSalesBook;
	}

	public void setVbSalesBook(VbSalesBook vbSalesBook) {
		this.vbSalesBook = vbSalesBook;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getSalesExecutive() {
		return this.salesExecutive;
	}

	public void setSalesExecutive(String salesExecutive) {
		this.salesExecutive = salesExecutive;
	}

	public Boolean getIsReturn() {
		return this.isReturn;
	}

	public void setIsReturn(Boolean isReturn) {
		this.isReturn = isReturn;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	public String getVehicleNo() {
		return this.vehicleNo;
	}

	public void setVehicleNo(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	public String getStartingReading() {
		return this.startingReading;
	}

	public void setStartingReading(String startingReading) {
		this.startingReading = startingReading;
	}

	public String getEndingReading() {
		return this.endingReading;
	}

	public void setEndingReading(String endingReading) {
		this.endingReading = endingReading;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getCrDescription() {
		return this.crDescription;
	}

	public void setCrDescription(String crDescription) {
		this.crDescription = crDescription;
	}

	public Set getVbDayBookChangeRequestAmounts() {
		return this.vbDayBookChangeRequestAmounts;
	}

	public void setVbDayBookChangeRequestAmounts(
			Set vbDayBookChangeRequestAmounts) {
		this.vbDayBookChangeRequestAmounts = vbDayBookChangeRequestAmounts;
	}

	public Set getVbDayBookChangeRequestProductses() {
		return this.vbDayBookChangeRequestProductses;
	}

	public void setVbDayBookChangeRequestProductses(
			Set vbDayBookChangeRequestProductses) {
		this.vbDayBookChangeRequestProductses = vbDayBookChangeRequestProductses;
	}

}
