package com.vekomy.vbooks.hibernate.model;

// Generated Jul 16, 2013 11:21:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbDayBookChangeRequestAmount generated by hbm2java
 */
public class VbDayBookChangeRequestAmount implements java.io.Serializable {

	private Integer id;
	private VbDayBookChangeRequest vbDayBookChangeRequest;
	private String executiveAllowances;
	private String driverAllowances;
	private String vehicleFuelExpenses;
	private String vehicleMeterReading;
	private String vehicleMaintenanceExpenses;
	private String offloadingLoadingCharges;
	private String dealerPartyExpenses;
	private String municipalCityCouncil;
	private String miscellaneousExpenses;
	private String reasonMiscellaneousExpenses;
	private String totalAllowances;
	private String customerTotalPayable;
	private String customerTotalReceived;
	private String customerTotalCredit;
	private String amountToBank;
	private String reasonAmountToBank;
	private String amountToFactory;
	private String closingBalance;

	public VbDayBookChangeRequestAmount() {
	}

	public VbDayBookChangeRequestAmount(
			VbDayBookChangeRequest vbDayBookChangeRequest) {
		this.vbDayBookChangeRequest = vbDayBookChangeRequest;
	}

	public VbDayBookChangeRequestAmount(
			VbDayBookChangeRequest vbDayBookChangeRequest,
			String executiveAllowances, String driverAllowances,
			String vehicleFuelExpenses, String vehicleMeterReading,
			String vehicleMaintenanceExpenses, String offloadingLoadingCharges,
			String dealerPartyExpenses, String municipalCityCouncil,
			String miscellaneousExpenses, String reasonMiscellaneousExpenses,
			String totalAllowances, String customerTotalPayable,
			String customerTotalReceived, String customerTotalCredit,
			String amountToBank, String reasonAmountToBank,
			String amountToFactory, String closingBalance) {
		this.vbDayBookChangeRequest = vbDayBookChangeRequest;
		this.executiveAllowances = executiveAllowances;
		this.driverAllowances = driverAllowances;
		this.vehicleFuelExpenses = vehicleFuelExpenses;
		this.vehicleMeterReading = vehicleMeterReading;
		this.vehicleMaintenanceExpenses = vehicleMaintenanceExpenses;
		this.offloadingLoadingCharges = offloadingLoadingCharges;
		this.dealerPartyExpenses = dealerPartyExpenses;
		this.municipalCityCouncil = municipalCityCouncil;
		this.miscellaneousExpenses = miscellaneousExpenses;
		this.reasonMiscellaneousExpenses = reasonMiscellaneousExpenses;
		this.totalAllowances = totalAllowances;
		this.customerTotalPayable = customerTotalPayable;
		this.customerTotalReceived = customerTotalReceived;
		this.customerTotalCredit = customerTotalCredit;
		this.amountToBank = amountToBank;
		this.reasonAmountToBank = reasonAmountToBank;
		this.amountToFactory = amountToFactory;
		this.closingBalance = closingBalance;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbDayBookChangeRequest getVbDayBookChangeRequest() {
		return this.vbDayBookChangeRequest;
	}

	public void setVbDayBookChangeRequest(
			VbDayBookChangeRequest vbDayBookChangeRequest) {
		this.vbDayBookChangeRequest = vbDayBookChangeRequest;
	}

	public String getExecutiveAllowances() {
		return this.executiveAllowances;
	}

	public void setExecutiveAllowances(String executiveAllowances) {
		this.executiveAllowances = executiveAllowances;
	}

	public String getDriverAllowances() {
		return this.driverAllowances;
	}

	public void setDriverAllowances(String driverAllowances) {
		this.driverAllowances = driverAllowances;
	}

	public String getVehicleFuelExpenses() {
		return this.vehicleFuelExpenses;
	}

	public void setVehicleFuelExpenses(String vehicleFuelExpenses) {
		this.vehicleFuelExpenses = vehicleFuelExpenses;
	}

	public String getVehicleMeterReading() {
		return this.vehicleMeterReading;
	}

	public void setVehicleMeterReading(String vehicleMeterReading) {
		this.vehicleMeterReading = vehicleMeterReading;
	}

	public String getVehicleMaintenanceExpenses() {
		return this.vehicleMaintenanceExpenses;
	}

	public void setVehicleMaintenanceExpenses(String vehicleMaintenanceExpenses) {
		this.vehicleMaintenanceExpenses = vehicleMaintenanceExpenses;
	}

	public String getOffloadingLoadingCharges() {
		return this.offloadingLoadingCharges;
	}

	public void setOffloadingLoadingCharges(String offloadingLoadingCharges) {
		this.offloadingLoadingCharges = offloadingLoadingCharges;
	}

	public String getDealerPartyExpenses() {
		return this.dealerPartyExpenses;
	}

	public void setDealerPartyExpenses(String dealerPartyExpenses) {
		this.dealerPartyExpenses = dealerPartyExpenses;
	}

	public String getMunicipalCityCouncil() {
		return this.municipalCityCouncil;
	}

	public void setMunicipalCityCouncil(String municipalCityCouncil) {
		this.municipalCityCouncil = municipalCityCouncil;
	}

	public String getMiscellaneousExpenses() {
		return this.miscellaneousExpenses;
	}

	public void setMiscellaneousExpenses(String miscellaneousExpenses) {
		this.miscellaneousExpenses = miscellaneousExpenses;
	}

	public String getReasonMiscellaneousExpenses() {
		return this.reasonMiscellaneousExpenses;
	}

	public void setReasonMiscellaneousExpenses(
			String reasonMiscellaneousExpenses) {
		this.reasonMiscellaneousExpenses = reasonMiscellaneousExpenses;
	}

	public String getTotalAllowances() {
		return this.totalAllowances;
	}

	public void setTotalAllowances(String totalAllowances) {
		this.totalAllowances = totalAllowances;
	}

	public String getCustomerTotalPayable() {
		return this.customerTotalPayable;
	}

	public void setCustomerTotalPayable(String customerTotalPayable) {
		this.customerTotalPayable = customerTotalPayable;
	}

	public String getCustomerTotalReceived() {
		return this.customerTotalReceived;
	}

	public void setCustomerTotalReceived(String customerTotalReceived) {
		this.customerTotalReceived = customerTotalReceived;
	}

	public String getCustomerTotalCredit() {
		return this.customerTotalCredit;
	}

	public void setCustomerTotalCredit(String customerTotalCredit) {
		this.customerTotalCredit = customerTotalCredit;
	}

	public String getAmountToBank() {
		return this.amountToBank;
	}

	public void setAmountToBank(String amountToBank) {
		this.amountToBank = amountToBank;
	}

	public String getReasonAmountToBank() {
		return this.reasonAmountToBank;
	}

	public void setReasonAmountToBank(String reasonAmountToBank) {
		this.reasonAmountToBank = reasonAmountToBank;
	}

	public String getAmountToFactory() {
		return this.amountToFactory;
	}

	public void setAmountToFactory(String amountToFactory) {
		this.amountToFactory = amountToFactory;
	}

	public String getClosingBalance() {
		return this.closingBalance;
	}

	public void setClosingBalance(String closingBalance) {
		this.closingBalance = closingBalance;
	}

}
