package com.vekomy.vbooks.hibernate.model;

// Generated Nov 19, 2013 10:32:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbDayBookChangeRequestProducts generated by hbm2java
 */
public class VbDayBookChangeRequestProducts implements java.io.Serializable {

	private Integer id;
	private VbDayBookChangeRequest vbDayBookChangeRequest;
	private String productName;
	private String batchNumber;
	private String openingStock;
	private String productsToCustomer;
	private String productsToFactory;
	private String closingStock;
	private String productRemarks;

	public VbDayBookChangeRequestProducts() {
	}

	public VbDayBookChangeRequestProducts(
			VbDayBookChangeRequest vbDayBookChangeRequest, String batchNumber) {
		this.vbDayBookChangeRequest = vbDayBookChangeRequest;
		this.batchNumber = batchNumber;
	}

	public VbDayBookChangeRequestProducts(
			VbDayBookChangeRequest vbDayBookChangeRequest, String productName,
			String batchNumber, String openingStock, String productsToCustomer,
			String productsToFactory, String closingStock, String productRemarks) {
		this.vbDayBookChangeRequest = vbDayBookChangeRequest;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.openingStock = openingStock;
		this.productsToCustomer = productsToCustomer;
		this.productsToFactory = productsToFactory;
		this.closingStock = closingStock;
		this.productRemarks = productRemarks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbDayBookChangeRequest getVbDayBookChangeRequest() {
		return this.vbDayBookChangeRequest;
	}

	public void setVbDayBookChangeRequest(
			VbDayBookChangeRequest vbDayBookChangeRequest) {
		this.vbDayBookChangeRequest = vbDayBookChangeRequest;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getBatchNumber() {
		return this.batchNumber;
	}

	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber;
	}

	public String getOpeningStock() {
		return this.openingStock;
	}

	public void setOpeningStock(String openingStock) {
		this.openingStock = openingStock;
	}

	public String getProductsToCustomer() {
		return this.productsToCustomer;
	}

	public void setProductsToCustomer(String productsToCustomer) {
		this.productsToCustomer = productsToCustomer;
	}

	public String getProductsToFactory() {
		return this.productsToFactory;
	}

	public void setProductsToFactory(String productsToFactory) {
		this.productsToFactory = productsToFactory;
	}

	public String getClosingStock() {
		return this.closingStock;
	}

	public void setClosingStock(String closingStock) {
		this.closingStock = closingStock;
	}

	public String getProductRemarks() {
		return this.productRemarks;
	}

	public void setProductRemarks(String productRemarks) {
		this.productRemarks = productRemarks;
	}

}
