package com.vekomy.vbooks.hibernate.model;

// Generated Jul 16, 2013 11:21:50 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VbDayBook generated by hbm2java
 */
public class VbDayBook implements java.io.Serializable {

	private Integer id;
	private VbSalesBook vbSalesBook;
	private VbOrganization vbOrganization;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private String salesExecutive;
	private Boolean isReturn;
	private String driverName;
	private String vehicleNo;
	private float startingReading;
	private float endingReading;
	private String remarks;
	private Set vbDayBookProductses = new HashSet(0);
	private Set vbDayBookAmounts = new HashSet(0);

	public VbDayBook() {
	}

	public VbDayBook(VbSalesBook vbSalesBook, VbOrganization vbOrganization,
			Date modifiedOn, String salesExecutive, String vehicleNo,
			float startingReading, float endingReading) {
		this.vbSalesBook = vbSalesBook;
		this.vbOrganization = vbOrganization;
		this.modifiedOn = modifiedOn;
		this.salesExecutive = salesExecutive;
		this.vehicleNo = vehicleNo;
		this.startingReading = startingReading;
		this.endingReading = endingReading;
	}

	public VbDayBook(VbSalesBook vbSalesBook, VbOrganization vbOrganization,
			Date createdOn, String createdBy, Date modifiedOn,
			String modifiedBy, String salesExecutive, Boolean isReturn,
			String driverName, String vehicleNo, float startingReading,
			float endingReading, String remarks, Set vbDayBookProductses,
			Set vbDayBookAmounts) {
		this.vbSalesBook = vbSalesBook;
		this.vbOrganization = vbOrganization;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.salesExecutive = salesExecutive;
		this.isReturn = isReturn;
		this.driverName = driverName;
		this.vehicleNo = vehicleNo;
		this.startingReading = startingReading;
		this.endingReading = endingReading;
		this.remarks = remarks;
		this.vbDayBookProductses = vbDayBookProductses;
		this.vbDayBookAmounts = vbDayBookAmounts;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbSalesBook getVbSalesBook() {
		return this.vbSalesBook;
	}

	public void setVbSalesBook(VbSalesBook vbSalesBook) {
		this.vbSalesBook = vbSalesBook;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getSalesExecutive() {
		return this.salesExecutive;
	}

	public void setSalesExecutive(String salesExecutive) {
		this.salesExecutive = salesExecutive;
	}

	public Boolean getIsReturn() {
		return this.isReturn;
	}

	public void setIsReturn(Boolean isReturn) {
		this.isReturn = isReturn;
	}

	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	public String getVehicleNo() {
		return this.vehicleNo;
	}

	public void setVehicleNo(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	public float getStartingReading() {
		return this.startingReading;
	}

	public void setStartingReading(float startingReading) {
		this.startingReading = startingReading;
	}

	public float getEndingReading() {
		return this.endingReading;
	}

	public void setEndingReading(float endingReading) {
		this.endingReading = endingReading;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public Set getVbDayBookProductses() {
		return this.vbDayBookProductses;
	}

	public void setVbDayBookProductses(Set vbDayBookProductses) {
		this.vbDayBookProductses = vbDayBookProductses;
	}

	public Set getVbDayBookAmounts() {
		return this.vbDayBookAmounts;
	}

	public void setVbDayBookAmounts(Set vbDayBookAmounts) {
		this.vbDayBookAmounts = vbDayBookAmounts;
	}

}
