package com.vekomy.vbooks.hibernate.model;

// Generated Jul 16, 2013 11:21:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbDeliveryNoteChangeRequestProducts generated by hbm2java
 */
public class VbDeliveryNoteChangeRequestProducts implements
		java.io.Serializable {

	private Integer id;
	private VbDeliveryNoteChangeRequest vbDeliveryNoteChangeRequest;
	private String productName;
	private String batchNumber;
	private String productQty;
	private String bonusQty;
	private String bonusReason;
	private String productCost;
	private String totalCost;

	public VbDeliveryNoteChangeRequestProducts() {
	}

	public VbDeliveryNoteChangeRequestProducts(
			VbDeliveryNoteChangeRequest vbDeliveryNoteChangeRequest,
			String productName, String batchNumber, String productQty,
			String productCost, String totalCost) {
		this.vbDeliveryNoteChangeRequest = vbDeliveryNoteChangeRequest;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.productQty = productQty;
		this.productCost = productCost;
		this.totalCost = totalCost;
	}

	public VbDeliveryNoteChangeRequestProducts(
			VbDeliveryNoteChangeRequest vbDeliveryNoteChangeRequest,
			String productName, String batchNumber, String productQty,
			String bonusQty, String bonusReason, String productCost,
			String totalCost) {
		this.vbDeliveryNoteChangeRequest = vbDeliveryNoteChangeRequest;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.productQty = productQty;
		this.bonusQty = bonusQty;
		this.bonusReason = bonusReason;
		this.productCost = productCost;
		this.totalCost = totalCost;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbDeliveryNoteChangeRequest getVbDeliveryNoteChangeRequest() {
		return this.vbDeliveryNoteChangeRequest;
	}

	public void setVbDeliveryNoteChangeRequest(
			VbDeliveryNoteChangeRequest vbDeliveryNoteChangeRequest) {
		this.vbDeliveryNoteChangeRequest = vbDeliveryNoteChangeRequest;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getBatchNumber() {
		return this.batchNumber;
	}

	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber;
	}

	public String getProductQty() {
		return this.productQty;
	}

	public void setProductQty(String productQty) {
		this.productQty = productQty;
	}

	public String getBonusQty() {
		return this.bonusQty;
	}

	public void setBonusQty(String bonusQty) {
		this.bonusQty = bonusQty;
	}

	public String getBonusReason() {
		return this.bonusReason;
	}

	public void setBonusReason(String bonusReason) {
		this.bonusReason = bonusReason;
	}

	public String getProductCost() {
		return this.productCost;
	}

	public void setProductCost(String productCost) {
		this.productCost = productCost;
	}

	public String getTotalCost() {
		return this.totalCost;
	}

	public void setTotalCost(String totalCost) {
		this.totalCost = totalCost;
	}

}
