package com.vekomy.vbooks.hibernate.model;

// Generated Nov 19, 2013 10:32:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VbEmployee generated by hbm2java
 */
public class VbEmployee implements java.io.Serializable {

	private Integer id;
	private VbOrganization vbOrganization;
	private String username;
	private String firstName;
	private String middleName;
	private String lastName;
	private String employeeNumber;
	private String employeeType;
	private int employeeHierarchyLevel;
	private String employeeEmail;
	private Character gender;
	private Integer grantedDays;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private Set<VbSystemAlertsNotifications> vbSystemAlertsNotificationses = new HashSet<VbSystemAlertsNotifications>(
			0);
	private Set<VbUserDefinedAlertsNotifications> vbUserDefinedAlertsNotificationses = new HashSet<VbUserDefinedAlertsNotifications>(
			0);
	private Set<VbEmployeeAddress> vbEmployeeAddresses = new HashSet<VbEmployeeAddress>(
			0);
	private Set<VbEmployeeCustomer> vbEmployeeCustomers = new HashSet<VbEmployeeCustomer>(
			0);
	private Set<VbAssignOrganizations> vbAssignOrganizationses = new HashSet<VbAssignOrganizations>(
			0);
	private Set<VbEmployeeDetail> vbEmployeeDetails = new HashSet<VbEmployeeDetail>(
			0);

	public VbEmployee() {
	}

	public VbEmployee(String username, String firstName, String lastName,
			String employeeType, int employeeHierarchyLevel,
			String employeeEmail, Date modifiedOn) {
		this.username = username;
		this.firstName = firstName;
		this.lastName = lastName;
		this.employeeType = employeeType;
		this.employeeHierarchyLevel = employeeHierarchyLevel;
		this.employeeEmail = employeeEmail;
		this.modifiedOn = modifiedOn;
	}

	public VbEmployee(
			VbOrganization vbOrganization,
			String username,
			String firstName,
			String middleName,
			String lastName,
			String employeeNumber,
			String employeeType,
			int employeeHierarchyLevel,
			String employeeEmail,
			Character gender,
			Integer grantedDays,
			Date createdOn,
			String createdBy,
			Date modifiedOn,
			String modifiedBy,
			Set<VbSystemAlertsNotifications> vbSystemAlertsNotificationses,
			Set<VbUserDefinedAlertsNotifications> vbUserDefinedAlertsNotificationses,
			Set<VbEmployeeAddress> vbEmployeeAddresses,
			Set<VbEmployeeCustomer> vbEmployeeCustomers,
			Set<VbAssignOrganizations> vbAssignOrganizationses,
			Set<VbEmployeeDetail> vbEmployeeDetails) {
		this.vbOrganization = vbOrganization;
		this.username = username;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.employeeNumber = employeeNumber;
		this.employeeType = employeeType;
		this.employeeHierarchyLevel = employeeHierarchyLevel;
		this.employeeEmail = employeeEmail;
		this.gender = gender;
		this.grantedDays = grantedDays;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.vbSystemAlertsNotificationses = vbSystemAlertsNotificationses;
		this.vbUserDefinedAlertsNotificationses = vbUserDefinedAlertsNotificationses;
		this.vbEmployeeAddresses = vbEmployeeAddresses;
		this.vbEmployeeCustomers = vbEmployeeCustomers;
		this.vbAssignOrganizationses = vbAssignOrganizationses;
		this.vbEmployeeDetails = vbEmployeeDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmployeeNumber() {
		return this.employeeNumber;
	}

	public void setEmployeeNumber(String employeeNumber) {
		this.employeeNumber = employeeNumber;
	}

	public String getEmployeeType() {
		return this.employeeType;
	}

	public void setEmployeeType(String employeeType) {
		this.employeeType = employeeType;
	}

	public int getEmployeeHierarchyLevel() {
		return this.employeeHierarchyLevel;
	}

	public void setEmployeeHierarchyLevel(int employeeHierarchyLevel) {
		this.employeeHierarchyLevel = employeeHierarchyLevel;
	}

	public String getEmployeeEmail() {
		return this.employeeEmail;
	}

	public void setEmployeeEmail(String employeeEmail) {
		this.employeeEmail = employeeEmail;
	}

	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	public Integer getGrantedDays() {
		return this.grantedDays;
	}

	public void setGrantedDays(Integer grantedDays) {
		this.grantedDays = grantedDays;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set<VbSystemAlertsNotifications> getVbSystemAlertsNotificationses() {
		return this.vbSystemAlertsNotificationses;
	}

	public void setVbSystemAlertsNotificationses(
			Set<VbSystemAlertsNotifications> vbSystemAlertsNotificationses) {
		this.vbSystemAlertsNotificationses = vbSystemAlertsNotificationses;
	}

	public Set<VbUserDefinedAlertsNotifications> getVbUserDefinedAlertsNotificationses() {
		return this.vbUserDefinedAlertsNotificationses;
	}

	public void setVbUserDefinedAlertsNotificationses(
			Set<VbUserDefinedAlertsNotifications> vbUserDefinedAlertsNotificationses) {
		this.vbUserDefinedAlertsNotificationses = vbUserDefinedAlertsNotificationses;
	}

	public Set<VbEmployeeAddress> getVbEmployeeAddresses() {
		return this.vbEmployeeAddresses;
	}

	public void setVbEmployeeAddresses(
			Set<VbEmployeeAddress> vbEmployeeAddresses) {
		this.vbEmployeeAddresses = vbEmployeeAddresses;
	}

	public Set<VbEmployeeCustomer> getVbEmployeeCustomers() {
		return this.vbEmployeeCustomers;
	}

	public void setVbEmployeeCustomers(
			Set<VbEmployeeCustomer> vbEmployeeCustomers) {
		this.vbEmployeeCustomers = vbEmployeeCustomers;
	}

	public Set<VbAssignOrganizations> getVbAssignOrganizationses() {
		return this.vbAssignOrganizationses;
	}

	public void setVbAssignOrganizationses(
			Set<VbAssignOrganizations> vbAssignOrganizationses) {
		this.vbAssignOrganizationses = vbAssignOrganizationses;
	}

	public Set<VbEmployeeDetail> getVbEmployeeDetails() {
		return this.vbEmployeeDetails;
	}

	public void setVbEmployeeDetails(Set<VbEmployeeDetail> vbEmployeeDetails) {
		this.vbEmployeeDetails = vbEmployeeDetails;
	}

}
