package com.vekomy.vbooks.hibernate.model;

// Generated Jul 16, 2013 11:21:50 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VbLoginTrack generated by hbm2java
 */
public class VbLoginTrack implements java.io.Serializable {

	private Integer id;
	private String username;
	private Date lastLoginTime;

	public VbLoginTrack() {
	}

	public VbLoginTrack(String username, Date lastLoginTime) {
		this.username = username;
		this.lastLoginTime = lastLoginTime;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public Date getLastLoginTime() {
		return this.lastLoginTime;
	}

	public void setLastLoginTime(Date lastLoginTime) {
		this.lastLoginTime = lastLoginTime;
	}

}
