package com.vekomy.vbooks.hibernate.model;

// Generated Nov 19, 2013 10:32:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VbNotifications generated by hbm2java
 */
public class VbNotifications implements java.io.Serializable {

	private Integer id;
	private String notificationType;
	private Set<VbSystemAlertsNotifications> vbSystemAlertsNotificationses = new HashSet<VbSystemAlertsNotifications>(
			0);
	private Set<VbUserDefinedAlertsNotifications> vbUserDefinedAlertsNotificationses = new HashSet<VbUserDefinedAlertsNotifications>(
			0);

	public VbNotifications() {
	}

	public VbNotifications(String notificationType) {
		this.notificationType = notificationType;
	}

	public VbNotifications(
			String notificationType,
			Set<VbSystemAlertsNotifications> vbSystemAlertsNotificationses,
			Set<VbUserDefinedAlertsNotifications> vbUserDefinedAlertsNotificationses) {
		this.notificationType = notificationType;
		this.vbSystemAlertsNotificationses = vbSystemAlertsNotificationses;
		this.vbUserDefinedAlertsNotificationses = vbUserDefinedAlertsNotificationses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getNotificationType() {
		return this.notificationType;
	}

	public void setNotificationType(String notificationType) {
		this.notificationType = notificationType;
	}

	public Set<VbSystemAlertsNotifications> getVbSystemAlertsNotificationses() {
		return this.vbSystemAlertsNotificationses;
	}

	public void setVbSystemAlertsNotificationses(
			Set<VbSystemAlertsNotifications> vbSystemAlertsNotificationses) {
		this.vbSystemAlertsNotificationses = vbSystemAlertsNotificationses;
	}

	public Set<VbUserDefinedAlertsNotifications> getVbUserDefinedAlertsNotificationses() {
		return this.vbUserDefinedAlertsNotificationses;
	}

	public void setVbUserDefinedAlertsNotificationses(
			Set<VbUserDefinedAlertsNotifications> vbUserDefinedAlertsNotificationses) {
		this.vbUserDefinedAlertsNotificationses = vbUserDefinedAlertsNotificationses;
	}

}
