package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbOrganizationMapping generated by hbm2java
 */
public class VbOrganizationMapping implements java.io.Serializable {

	/**
	 * long variable holds serialVersionUID.
	 */
	private static final long serialVersionUID = 6648864022791741533L;
	private Integer id;
	private String parent;
	/**
	 * @return the parent
	 */
	public String getParent() {
		return parent;
	}

	/**
	 * @param parent the parent to set
	 */
	public void setParent(String parent) {
		this.parent = parent;
	}

	private VbOrganization vbOrganizationBySubBranchId;
	private VbOrganization vbOrganizationByMainBranchId;

	public VbOrganizationMapping() {
	}

	public VbOrganizationMapping(VbOrganization vbOrganizationBySubBranchId,
			VbOrganization vbOrganizationByMainBranchId) {
		this.vbOrganizationBySubBranchId = vbOrganizationBySubBranchId;
		this.vbOrganizationByMainBranchId = vbOrganizationByMainBranchId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbOrganization getVbOrganizationBySubBranchId() {
		return this.vbOrganizationBySubBranchId;
	}

	public void setVbOrganizationBySubBranchId(
			VbOrganization vbOrganizationBySubBranchId) {
		this.vbOrganizationBySubBranchId = vbOrganizationBySubBranchId;
	}

	public VbOrganization getVbOrganizationByMainBranchId() {
		return this.vbOrganizationByMainBranchId;
	}

	public void setVbOrganizationByMainBranchId(
			VbOrganization vbOrganizationByMainBranchId) {
		this.vbOrganizationByMainBranchId = vbOrganizationByMainBranchId;
	}

}
