package com.vekomy.vbooks.hibernate.model;

// Generated Jul 16, 2013 11:21:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbOrganizationMapping generated by hbm2java
 */
public class VbOrganizationMapping implements java.io.Serializable {

	private Integer id;
	private VbOrganization vbOrganizationBySubBranchId;
	private VbOrganization vbOrganizationByMainBranchId;

	public VbOrganizationMapping() {
	}

	public VbOrganizationMapping(VbOrganization vbOrganizationBySubBranchId,
			VbOrganization vbOrganizationByMainBranchId) {
		this.vbOrganizationBySubBranchId = vbOrganizationBySubBranchId;
		this.vbOrganizationByMainBranchId = vbOrganizationByMainBranchId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbOrganization getVbOrganizationBySubBranchId() {
		return this.vbOrganizationBySubBranchId;
	}

	public void setVbOrganizationBySubBranchId(
			VbOrganization vbOrganizationBySubBranchId) {
		this.vbOrganizationBySubBranchId = vbOrganizationBySubBranchId;
	}

	public VbOrganization getVbOrganizationByMainBranchId() {
		return this.vbOrganizationByMainBranchId;
	}

	public void setVbOrganizationByMainBranchId(
			VbOrganization vbOrganizationByMainBranchId) {
		this.vbOrganizationByMainBranchId = vbOrganizationByMainBranchId;
	}

}
