package com.vekomy.vbooks.hibernate.model;

// Generated Nov 19, 2013 10:32:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VbRole generated by hbm2java
 */
public class VbRole implements java.io.Serializable {

	private Integer id;
	private String roleName;
	private String description;
	private Set<VbSystemAlertsNotifications> vbSystemAlertsNotificationses = new HashSet<VbSystemAlertsNotifications>(
			0);
	private Set<VbAuthority> vbAuthorities = new HashSet<VbAuthority>(0);
	private Set<VbUserDefinedAlertsNotifications> vbUserDefinedAlertsNotificationses = new HashSet<VbUserDefinedAlertsNotifications>(
			0);
	private Set<VbRoleModuleMapping> vbRoleModuleMappings = new HashSet<VbRoleModuleMapping>(
			0);

	public VbRole() {
	}

	public VbRole(String roleName) {
		this.roleName = roleName;
	}

	public VbRole(
			String roleName,
			String description,
			Set<VbSystemAlertsNotifications> vbSystemAlertsNotificationses,
			Set<VbAuthority> vbAuthorities,
			Set<VbUserDefinedAlertsNotifications> vbUserDefinedAlertsNotificationses,
			Set<VbRoleModuleMapping> vbRoleModuleMappings) {
		this.roleName = roleName;
		this.description = description;
		this.vbSystemAlertsNotificationses = vbSystemAlertsNotificationses;
		this.vbAuthorities = vbAuthorities;
		this.vbUserDefinedAlertsNotificationses = vbUserDefinedAlertsNotificationses;
		this.vbRoleModuleMappings = vbRoleModuleMappings;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set<VbSystemAlertsNotifications> getVbSystemAlertsNotificationses() {
		return this.vbSystemAlertsNotificationses;
	}

	public void setVbSystemAlertsNotificationses(
			Set<VbSystemAlertsNotifications> vbSystemAlertsNotificationses) {
		this.vbSystemAlertsNotificationses = vbSystemAlertsNotificationses;
	}

	public Set<VbAuthority> getVbAuthorities() {
		return this.vbAuthorities;
	}

	public void setVbAuthorities(Set<VbAuthority> vbAuthorities) {
		this.vbAuthorities = vbAuthorities;
	}

	public Set<VbUserDefinedAlertsNotifications> getVbUserDefinedAlertsNotificationses() {
		return this.vbUserDefinedAlertsNotificationses;
	}

	public void setVbUserDefinedAlertsNotificationses(
			Set<VbUserDefinedAlertsNotifications> vbUserDefinedAlertsNotificationses) {
		this.vbUserDefinedAlertsNotificationses = vbUserDefinedAlertsNotificationses;
	}

	public Set<VbRoleModuleMapping> getVbRoleModuleMappings() {
		return this.vbRoleModuleMappings;
	}

	public void setVbRoleModuleMappings(
			Set<VbRoleModuleMapping> vbRoleModuleMappings) {
		this.vbRoleModuleMappings = vbRoleModuleMappings;
	}

}
