package com.vekomy.vbooks.hibernate.model;

// Generated Nov 19, 2013 10:32:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VbSalesReturnChangeRequest generated by hbm2java
 */
public class VbSalesReturnChangeRequest implements java.io.Serializable {

	private Integer id;
	private VbSalesBook vbSalesBook;
	private VbOrganization vbOrganization;
	private String invoiceNo;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private String businessName;
	private String invoiceName;
	private String productsGrandTotal;
	private String status;
	private String remarks;
	private String crDescription;
	private Set<VbSalesReturnChangeRequestProducts> vbSalesReturnChangeRequestProductses = new HashSet<VbSalesReturnChangeRequestProducts>(
			0);

	public VbSalesReturnChangeRequest() {
	}

	public VbSalesReturnChangeRequest(VbSalesBook vbSalesBook,
			VbOrganization vbOrganization, String invoiceNo, Date modifiedOn,
			String businessName, String invoiceName, String productsGrandTotal) {
		this.vbSalesBook = vbSalesBook;
		this.vbOrganization = vbOrganization;
		this.invoiceNo = invoiceNo;
		this.modifiedOn = modifiedOn;
		this.businessName = businessName;
		this.invoiceName = invoiceName;
		this.productsGrandTotal = productsGrandTotal;
	}

	public VbSalesReturnChangeRequest(
			VbSalesBook vbSalesBook,
			VbOrganization vbOrganization,
			String invoiceNo,
			Date createdOn,
			String createdBy,
			Date modifiedOn,
			String modifiedBy,
			String businessName,
			String invoiceName,
			String productsGrandTotal,
			String status,
			String remarks,
			String crDescription,
			Set<VbSalesReturnChangeRequestProducts> vbSalesReturnChangeRequestProductses) {
		this.vbSalesBook = vbSalesBook;
		this.vbOrganization = vbOrganization;
		this.invoiceNo = invoiceNo;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.businessName = businessName;
		this.invoiceName = invoiceName;
		this.productsGrandTotal = productsGrandTotal;
		this.status = status;
		this.remarks = remarks;
		this.crDescription = crDescription;
		this.vbSalesReturnChangeRequestProductses = vbSalesReturnChangeRequestProductses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbSalesBook getVbSalesBook() {
		return this.vbSalesBook;
	}

	public void setVbSalesBook(VbSalesBook vbSalesBook) {
		this.vbSalesBook = vbSalesBook;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public String getInvoiceName() {
		return this.invoiceName;
	}

	public void setInvoiceName(String invoiceName) {
		this.invoiceName = invoiceName;
	}

	public String getProductsGrandTotal() {
		return this.productsGrandTotal;
	}

	public void setProductsGrandTotal(String productsGrandTotal) {
		this.productsGrandTotal = productsGrandTotal;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

	public String getCrDescription() {
		return this.crDescription;
	}

	public void setCrDescription(String crDescription) {
		this.crDescription = crDescription;
	}

	public Set<VbSalesReturnChangeRequestProducts> getVbSalesReturnChangeRequestProductses() {
		return this.vbSalesReturnChangeRequestProductses;
	}

	public void setVbSalesReturnChangeRequestProductses(
			Set<VbSalesReturnChangeRequestProducts> vbSalesReturnChangeRequestProductses) {
		this.vbSalesReturnChangeRequestProductses = vbSalesReturnChangeRequestProductses;
	}

}
