package com.vekomy.vbooks.hibernate.model;

// Generated Jul 16, 2013 11:21:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbSalesBookProducts generated by hbm2java
 */
public class VbSalesBookProducts implements java.io.Serializable {

	private Integer id;
	private VbSalesBook vbSalesBook;
	private String productName;
	private String batchNumber;
	private Integer qtyAllotted;
	private Integer qtyOpeningBalance;
	private Integer qtySold;
	private Integer qtyToFactory;
	private Integer qtyClosingBalance;
	private String remarks;

	public VbSalesBookProducts() {
	}

	public VbSalesBookProducts(VbSalesBook vbSalesBook, String productName,
			String batchNumber) {
		this.vbSalesBook = vbSalesBook;
		this.productName = productName;
		this.batchNumber = batchNumber;
	}

	public VbSalesBookProducts(VbSalesBook vbSalesBook, String productName,
			String batchNumber, Integer qtyAllotted, Integer qtyOpeningBalance,
			Integer qtySold, Integer qtyToFactory, Integer qtyClosingBalance,
			String remarks) {
		this.vbSalesBook = vbSalesBook;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.qtyAllotted = qtyAllotted;
		this.qtyOpeningBalance = qtyOpeningBalance;
		this.qtySold = qtySold;
		this.qtyToFactory = qtyToFactory;
		this.qtyClosingBalance = qtyClosingBalance;
		this.remarks = remarks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbSalesBook getVbSalesBook() {
		return this.vbSalesBook;
	}

	public void setVbSalesBook(VbSalesBook vbSalesBook) {
		this.vbSalesBook = vbSalesBook;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getBatchNumber() {
		return this.batchNumber;
	}

	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber;
	}

	public Integer getQtyAllotted() {
		return this.qtyAllotted;
	}

	public void setQtyAllotted(Integer qtyAllotted) {
		this.qtyAllotted = qtyAllotted;
	}

	public Integer getQtyOpeningBalance() {
		return this.qtyOpeningBalance;
	}

	public void setQtyOpeningBalance(Integer qtyOpeningBalance) {
		this.qtyOpeningBalance = qtyOpeningBalance;
	}

	public Integer getQtySold() {
		return this.qtySold;
	}

	public void setQtySold(Integer qtySold) {
		this.qtySold = qtySold;
	}

	public Integer getQtyToFactory() {
		return this.qtyToFactory;
	}

	public void setQtyToFactory(Integer qtyToFactory) {
		this.qtyToFactory = qtyToFactory;
	}

	public Integer getQtyClosingBalance() {
		return this.qtyClosingBalance;
	}

	public void setQtyClosingBalance(Integer qtyClosingBalance) {
		this.qtyClosingBalance = qtyClosingBalance;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
