package com.vekomy.vbooks.hibernate.model;

// Generated Nov 19, 2013 10:32:53 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VbSalesBook generated by hbm2java
 */
public class VbSalesBook implements java.io.Serializable {

	private Integer id;
	private VbOrganization vbOrganization;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private String salesExecutive;
	private String salesBookNo;
	private Float advance;
	private Float openingBalance;
	private Float closingBalance;
	private Integer flag;
	private Integer cycleId;
	private String allotmentType;
	private Set<VbDayBookChangeRequest> vbDayBookChangeRequests = new HashSet<VbDayBookChangeRequest>(
			0);
	private Set<VbJournal> vbJournals = new HashSet<VbJournal>(0);
	private Set<VbDayBook> vbDayBooks = new HashSet<VbDayBook>(0);
	private Set<VbDeliveryNote> vbDeliveryNotes = new HashSet<VbDeliveryNote>(0);
	private Set<VbCashDayBookCr> vbCashDayBookCrs = new HashSet<VbCashDayBookCr>(
			0);
	private Set<VbDeliveryNoteChangeRequest> vbDeliveryNoteChangeRequests = new HashSet<VbDeliveryNoteChangeRequest>(
			0);
	private Set<VbSalesReturn> vbSalesReturns = new HashSet<VbSalesReturn>(0);
	private Set<VbCashDayBook> vbCashDayBooks = new HashSet<VbCashDayBook>(0);
	private Set<VbJournalChangeRequest> vbJournalChangeRequests = new HashSet<VbJournalChangeRequest>(
			0);
	private Set<VbSalesBookProducts> vbSalesBookProductses = new HashSet<VbSalesBookProducts>(
			0);
	private Set<VbSalesReturnChangeRequest> vbSalesReturnChangeRequests = new HashSet<VbSalesReturnChangeRequest>(
			0);

	public VbSalesBook() {
	}

	public VbSalesBook(VbOrganization vbOrganization, Date modifiedOn,
			String salesExecutive, String allotmentType) {
		this.vbOrganization = vbOrganization;
		this.modifiedOn = modifiedOn;
		this.salesExecutive = salesExecutive;
		this.allotmentType = allotmentType;
	}

	public VbSalesBook(VbOrganization vbOrganization, Date createdOn,
			String createdBy, Date modifiedOn, String modifiedBy,
			String salesExecutive, String salesBookNo, Float advance,
			Float openingBalance, Float closingBalance, Integer flag,
			Integer cycleId, String allotmentType,
			Set<VbDayBookChangeRequest> vbDayBookChangeRequests,
			Set<VbJournal> vbJournals, Set<VbDayBook> vbDayBooks,
			Set<VbDeliveryNote> vbDeliveryNotes,
			Set<VbCashDayBookCr> vbCashDayBookCrs,
			Set<VbDeliveryNoteChangeRequest> vbDeliveryNoteChangeRequests,
			Set<VbSalesReturn> vbSalesReturns,
			Set<VbCashDayBook> vbCashDayBooks,
			Set<VbJournalChangeRequest> vbJournalChangeRequests,
			Set<VbSalesBookProducts> vbSalesBookProductses,
			Set<VbSystemNotifications> vbSystemNotificationses,
			Set<VbSalesReturnChangeRequest> vbSalesReturnChangeRequests) {
		this.vbOrganization = vbOrganization;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.salesExecutive = salesExecutive;
		this.salesBookNo = salesBookNo;
		this.advance = advance;
		this.openingBalance = openingBalance;
		this.closingBalance = closingBalance;
		this.flag = flag;
		this.cycleId = cycleId;
		this.allotmentType = allotmentType;
		this.vbDayBookChangeRequests = vbDayBookChangeRequests;
		this.vbJournals = vbJournals;
		this.vbDayBooks = vbDayBooks;
		this.vbDeliveryNotes = vbDeliveryNotes;
		this.vbCashDayBookCrs = vbCashDayBookCrs;
		this.vbDeliveryNoteChangeRequests = vbDeliveryNoteChangeRequests;
		this.vbSalesReturns = vbSalesReturns;
		this.vbCashDayBooks = vbCashDayBooks;
		this.vbJournalChangeRequests = vbJournalChangeRequests;
		this.vbSalesBookProductses = vbSalesBookProductses;
		this.vbSalesReturnChangeRequests = vbSalesReturnChangeRequests;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getSalesExecutive() {
		return this.salesExecutive;
	}

	public void setSalesExecutive(String salesExecutive) {
		this.salesExecutive = salesExecutive;
	}

	public String getSalesBookNo() {
		return this.salesBookNo;
	}

	public void setSalesBookNo(String salesBookNo) {
		this.salesBookNo = salesBookNo;
	}

	public Float getAdvance() {
		return this.advance;
	}

	public void setAdvance(Float advance) {
		this.advance = advance;
	}

	public Float getOpeningBalance() {
		return this.openingBalance;
	}

	public void setOpeningBalance(Float openingBalance) {
		this.openingBalance = openingBalance;
	}

	public Float getClosingBalance() {
		return this.closingBalance;
	}

	public void setClosingBalance(Float closingBalance) {
		this.closingBalance = closingBalance;
	}

	public Integer getFlag() {
		return this.flag;
	}

	public void setFlag(Integer flag) {
		this.flag = flag;
	}

	public Integer getCycleId() {
		return this.cycleId;
	}

	public void setCycleId(Integer cycleId) {
		this.cycleId = cycleId;
	}

	public String getAllotmentType() {
		return this.allotmentType;
	}

	public void setAllotmentType(String allotmentType) {
		this.allotmentType = allotmentType;
	}

	public Set<VbDayBookChangeRequest> getVbDayBookChangeRequests() {
		return this.vbDayBookChangeRequests;
	}

	public void setVbDayBookChangeRequests(
			Set<VbDayBookChangeRequest> vbDayBookChangeRequests) {
		this.vbDayBookChangeRequests = vbDayBookChangeRequests;
	}

	public Set<VbJournal> getVbJournals() {
		return this.vbJournals;
	}

	public void setVbJournals(Set<VbJournal> vbJournals) {
		this.vbJournals = vbJournals;
	}

	public Set<VbDayBook> getVbDayBooks() {
		return this.vbDayBooks;
	}

	public void setVbDayBooks(Set<VbDayBook> vbDayBooks) {
		this.vbDayBooks = vbDayBooks;
	}

	public Set<VbDeliveryNote> getVbDeliveryNotes() {
		return this.vbDeliveryNotes;
	}

	public void setVbDeliveryNotes(Set<VbDeliveryNote> vbDeliveryNotes) {
		this.vbDeliveryNotes = vbDeliveryNotes;
	}

	public Set<VbCashDayBookCr> getVbCashDayBookCrs() {
		return this.vbCashDayBookCrs;
	}

	public void setVbCashDayBookCrs(Set<VbCashDayBookCr> vbCashDayBookCrs) {
		this.vbCashDayBookCrs = vbCashDayBookCrs;
	}

	public Set<VbDeliveryNoteChangeRequest> getVbDeliveryNoteChangeRequests() {
		return this.vbDeliveryNoteChangeRequests;
	}

	public void setVbDeliveryNoteChangeRequests(
			Set<VbDeliveryNoteChangeRequest> vbDeliveryNoteChangeRequests) {
		this.vbDeliveryNoteChangeRequests = vbDeliveryNoteChangeRequests;
	}

	public Set<VbSalesReturn> getVbSalesReturns() {
		return this.vbSalesReturns;
	}

	public void setVbSalesReturns(Set<VbSalesReturn> vbSalesReturns) {
		this.vbSalesReturns = vbSalesReturns;
	}

	public Set<VbCashDayBook> getVbCashDayBooks() {
		return this.vbCashDayBooks;
	}

	public void setVbCashDayBooks(Set<VbCashDayBook> vbCashDayBooks) {
		this.vbCashDayBooks = vbCashDayBooks;
	}

	public Set<VbJournalChangeRequest> getVbJournalChangeRequests() {
		return this.vbJournalChangeRequests;
	}

	public void setVbJournalChangeRequests(
			Set<VbJournalChangeRequest> vbJournalChangeRequests) {
		this.vbJournalChangeRequests = vbJournalChangeRequests;
	}

	public Set<VbSalesBookProducts> getVbSalesBookProductses() {
		return this.vbSalesBookProductses;
	}

	public void setVbSalesBookProductses(
			Set<VbSalesBookProducts> vbSalesBookProductses) {
		this.vbSalesBookProductses = vbSalesBookProductses;
	}

	public Set<VbSalesReturnChangeRequest> getVbSalesReturnChangeRequests() {
		return this.vbSalesReturnChangeRequests;
	}

	public void setVbSalesReturnChangeRequests(
			Set<VbSalesReturnChangeRequest> vbSalesReturnChangeRequests) {
		this.vbSalesReturnChangeRequests = vbSalesReturnChangeRequests;
	}

}
