package com.vekomy.vbooks.hibernate.model;

// Generated Nov 19, 2013 10:32:53 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbSalesReturnChangeRequestProducts generated by hbm2java
 */
public class VbSalesReturnChangeRequestProducts implements java.io.Serializable {

	private Integer id;
	private VbSalesReturnChangeRequest vbSalesReturnChangeRequest;
	private String productName;
	private String batchNumber;
	private String damaged;
	private String resalable;
	private String totalQty;
	private String resalableCost;
	private String damagedCost;
	private String totalCost;

	public VbSalesReturnChangeRequestProducts() {
	}

	public VbSalesReturnChangeRequestProducts(
			VbSalesReturnChangeRequest vbSalesReturnChangeRequest,
			String productName, String batchNumber, String totalCost) {
		this.vbSalesReturnChangeRequest = vbSalesReturnChangeRequest;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.totalCost = totalCost;
	}

	public VbSalesReturnChangeRequestProducts(
			VbSalesReturnChangeRequest vbSalesReturnChangeRequest,
			String productName, String batchNumber, String damaged,
			String resalable, String totalQty, String resalableCost,
			String damagedCost, String totalCost) {
		this.vbSalesReturnChangeRequest = vbSalesReturnChangeRequest;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.damaged = damaged;
		this.resalable = resalable;
		this.totalQty = totalQty;
		this.resalableCost = resalableCost;
		this.damagedCost = damagedCost;
		this.totalCost = totalCost;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbSalesReturnChangeRequest getVbSalesReturnChangeRequest() {
		return this.vbSalesReturnChangeRequest;
	}

	public void setVbSalesReturnChangeRequest(
			VbSalesReturnChangeRequest vbSalesReturnChangeRequest) {
		this.vbSalesReturnChangeRequest = vbSalesReturnChangeRequest;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getBatchNumber() {
		return this.batchNumber;
	}

	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber;
	}

	public String getDamaged() {
		return this.damaged;
	}

	public void setDamaged(String damaged) {
		this.damaged = damaged;
	}

	public String getResalable() {
		return this.resalable;
	}

	public void setResalable(String resalable) {
		this.resalable = resalable;
	}

	public String getTotalQty() {
		return this.totalQty;
	}

	public void setTotalQty(String totalQty) {
		this.totalQty = totalQty;
	}

	public String getResalableCost() {
		return this.resalableCost;
	}

	public void setResalableCost(String resalableCost) {
		this.resalableCost = resalableCost;
	}

	public String getDamagedCost() {
		return this.damagedCost;
	}

	public void setDamagedCost(String damagedCost) {
		this.damagedCost = damagedCost;
	}

	public String getTotalCost() {
		return this.totalCost;
	}

	public void setTotalCost(String totalCost) {
		this.totalCost = totalCost;
	}

}
