package com.vekomy.vbooks.hibernate.model;

// Generated Jul 16, 2013 11:21:50 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VbSystemAlertsHistory generated by hbm2java
 */
public class VbSystemAlertsHistory implements java.io.Serializable {

	private Integer id;
	private VbSystemAlerts vbSystemAlerts;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private String reference;

	public VbSystemAlertsHistory() {
	}

	public VbSystemAlertsHistory(VbSystemAlerts vbSystemAlerts) {
		this.vbSystemAlerts = vbSystemAlerts;
	}

	public VbSystemAlertsHistory(VbSystemAlerts vbSystemAlerts, Date createdOn,
			String createdBy, Date modifiedOn, String modifiedBy,
			String reference) {
		this.vbSystemAlerts = vbSystemAlerts;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.reference = reference;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbSystemAlerts getVbSystemAlerts() {
		return this.vbSystemAlerts;
	}

	public void setVbSystemAlerts(VbSystemAlerts vbSystemAlerts) {
		this.vbSystemAlerts = vbSystemAlerts;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

}
