package com.vekomy.vbooks.hibernate.model;

// Generated Jul 16, 2013 11:21:50 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbUserDefinedAlertsNotifications generated by hbm2java
 */
public class VbUserDefinedAlertsNotifications implements java.io.Serializable {

	private Integer id;
	private VbEmployee vbEmployee;
	private VbRole vbRole;
	private VbUserDefinedAlerts vbUserDefinedAlerts;
	private VbNotifications vbNotifications;
	private Boolean mailsTo;
	private Boolean mailsCc;
	private Boolean mailsBcc;

	public VbUserDefinedAlertsNotifications() {
	}

	public VbUserDefinedAlertsNotifications(VbEmployee vbEmployee,
			VbRole vbRole, VbUserDefinedAlerts vbUserDefinedAlerts,
			VbNotifications vbNotifications) {
		this.vbEmployee = vbEmployee;
		this.vbRole = vbRole;
		this.vbUserDefinedAlerts = vbUserDefinedAlerts;
		this.vbNotifications = vbNotifications;
	}

	public VbUserDefinedAlertsNotifications(VbEmployee vbEmployee,
			VbRole vbRole, VbUserDefinedAlerts vbUserDefinedAlerts,
			VbNotifications vbNotifications, Boolean mailsTo, Boolean mailsCc,
			Boolean mailsBcc) {
		this.vbEmployee = vbEmployee;
		this.vbRole = vbRole;
		this.vbUserDefinedAlerts = vbUserDefinedAlerts;
		this.vbNotifications = vbNotifications;
		this.mailsTo = mailsTo;
		this.mailsCc = mailsCc;
		this.mailsBcc = mailsBcc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbEmployee getVbEmployee() {
		return this.vbEmployee;
	}

	public void setVbEmployee(VbEmployee vbEmployee) {
		this.vbEmployee = vbEmployee;
	}

	public VbRole getVbRole() {
		return this.vbRole;
	}

	public void setVbRole(VbRole vbRole) {
		this.vbRole = vbRole;
	}

	public VbUserDefinedAlerts getVbUserDefinedAlerts() {
		return this.vbUserDefinedAlerts;
	}

	public void setVbUserDefinedAlerts(VbUserDefinedAlerts vbUserDefinedAlerts) {
		this.vbUserDefinedAlerts = vbUserDefinedAlerts;
	}

	public VbNotifications getVbNotifications() {
		return this.vbNotifications;
	}

	public void setVbNotifications(VbNotifications vbNotifications) {
		this.vbNotifications = vbNotifications;
	}

	public Boolean getMailsTo() {
		return this.mailsTo;
	}

	public void setMailsTo(Boolean mailsTo) {
		this.mailsTo = mailsTo;
	}

	public Boolean getMailsCc() {
		return this.mailsCc;
	}

	public void setMailsCc(Boolean mailsCc) {
		this.mailsCc = mailsCc;
	}

	public Boolean getMailsBcc() {
		return this.mailsBcc;
	}

	public void setMailsBcc(Boolean mailsBcc) {
		this.mailsBcc = mailsBcc;
	}

}
