package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VbAlertTypeMySales generated by hbm2java
 */
public class VbAlertTypeMySales implements java.io.Serializable {

	private Integer id;
	private VbAlertType vbAlertType;
	private String alertMySales;
	private Set vbAlertTypeMySalesPages = new HashSet(0);
	private Set vbMySaleses = new HashSet(0);

	public VbAlertTypeMySales() {
	}

	public VbAlertTypeMySales(VbAlertType vbAlertType, String alertMySales) {
		this.vbAlertType = vbAlertType;
		this.alertMySales = alertMySales;
	}

	public VbAlertTypeMySales(VbAlertType vbAlertType, String alertMySales,
			Set vbAlertTypeMySalesPages, Set vbMySaleses) {
		this.vbAlertType = vbAlertType;
		this.alertMySales = alertMySales;
		this.vbAlertTypeMySalesPages = vbAlertTypeMySalesPages;
		this.vbMySaleses = vbMySaleses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbAlertType getVbAlertType() {
		return this.vbAlertType;
	}

	public void setVbAlertType(VbAlertType vbAlertType) {
		this.vbAlertType = vbAlertType;
	}

	public String getAlertMySales() {
		return this.alertMySales;
	}

	public void setAlertMySales(String alertMySales) {
		this.alertMySales = alertMySales;
	}

	public Set getVbAlertTypeMySalesPages() {
		return this.vbAlertTypeMySalesPages;
	}

	public void setVbAlertTypeMySalesPages(Set vbAlertTypeMySalesPages) {
		this.vbAlertTypeMySalesPages = vbAlertTypeMySalesPages;
	}

	public Set getVbMySaleses() {
		return this.vbMySaleses;
	}

	public void setVbMySaleses(Set vbMySaleses) {
		this.vbMySaleses = vbMySaleses;
	}

}
