package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VbAlertCategory generated by hbm2java
 */
public class VbAlertCategory implements java.io.Serializable {

	private Integer id;
	private String alertCategory;
	private Set vbAlertTypes = new HashSet(0);

	public VbAlertCategory() {
	}

	public VbAlertCategory(String alertCategory) {
		this.alertCategory = alertCategory;
	}

	public VbAlertCategory(String alertCategory, Set vbAlertTypes) {
		this.alertCategory = alertCategory;
		this.vbAlertTypes = vbAlertTypes;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getAlertCategory() {
		return this.alertCategory;
	}

	public void setAlertCategory(String alertCategory) {
		this.alertCategory = alertCategory;
	}

	public Set getVbAlertTypes() {
		return this.vbAlertTypes;
	}

	public void setVbAlertTypes(Set vbAlertTypes) {
		this.vbAlertTypes = vbAlertTypes;
	}

}
