package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VbAlertType generated by hbm2java
 */
public class VbAlertType implements java.io.Serializable {

	private Integer id;
	private VbAlertCategory vbAlertCategory;
	private String alertType;
	private Set vbUserDefinedAlertses = new HashSet(0);
	private Set vbAlertTypeMySaleses = new HashSet(0);
	private Set vbSystemAlertses = new HashSet(0);

	public VbAlertType() {
	}

	public VbAlertType(VbAlertCategory vbAlertCategory, String alertType) {
		this.vbAlertCategory = vbAlertCategory;
		this.alertType = alertType;
	}

	public VbAlertType(VbAlertCategory vbAlertCategory, String alertType,
			Set vbUserDefinedAlertses, Set vbAlertTypeMySaleses,
			Set vbSystemAlertses) {
		this.vbAlertCategory = vbAlertCategory;
		this.alertType = alertType;
		this.vbUserDefinedAlertses = vbUserDefinedAlertses;
		this.vbAlertTypeMySaleses = vbAlertTypeMySaleses;
		this.vbSystemAlertses = vbSystemAlertses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbAlertCategory getVbAlertCategory() {
		return this.vbAlertCategory;
	}

	public void setVbAlertCategory(VbAlertCategory vbAlertCategory) {
		this.vbAlertCategory = vbAlertCategory;
	}

	public String getAlertType() {
		return this.alertType;
	}

	public void setAlertType(String alertType) {
		this.alertType = alertType;
	}

	public Set getVbUserDefinedAlertses() {
		return this.vbUserDefinedAlertses;
	}

	public void setVbUserDefinedAlertses(Set vbUserDefinedAlertses) {
		this.vbUserDefinedAlertses = vbUserDefinedAlertses;
	}

	public Set getVbAlertTypeMySaleses() {
		return this.vbAlertTypeMySaleses;
	}

	public void setVbAlertTypeMySaleses(Set vbAlertTypeMySaleses) {
		this.vbAlertTypeMySaleses = vbAlertTypeMySaleses;
	}

	public Set getVbSystemAlertses() {
		return this.vbSystemAlertses;
	}

	public void setVbSystemAlertses(Set vbSystemAlertses) {
		this.vbSystemAlertses = vbSystemAlertses;
	}

}
