package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VbCashDayBook generated by hbm2java
 */
public class VbCashDayBook implements java.io.Serializable {

	/**
	 * long variable holds serialVersionUID.
	 */
	private static final long serialVersionUID = 8997761990030061035L;
	private Integer id;
	private VbSalesBook vbSalesBook;
	private VbOrganization vbOrganization;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private String dayBookType;
	private String valueOne;
	private String valueTwo;
	private String valueThree;
	private Set vbCashDayBookCrs = new HashSet(0);

	public VbCashDayBook() {
	}

	public VbCashDayBook(VbSalesBook vbSalesBook,
			VbOrganization vbOrganization, Date modifiedOn, String dayBookType) {
		this.vbSalesBook = vbSalesBook;
		this.vbOrganization = vbOrganization;
		this.modifiedOn = modifiedOn;
		this.dayBookType = dayBookType;
	}

	public VbCashDayBook(VbSalesBook vbSalesBook,
			VbOrganization vbOrganization, Date createdOn, String createdBy,
			Date modifiedOn, String modifiedBy, String dayBookType,
			String valueOne, String valueTwo, String valueThree,
			Set vbCashDayBookCrs) {
		this.vbSalesBook = vbSalesBook;
		this.vbOrganization = vbOrganization;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.dayBookType = dayBookType;
		this.valueOne = valueOne;
		this.valueTwo = valueTwo;
		this.valueThree = valueThree;
		this.vbCashDayBookCrs = vbCashDayBookCrs;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbSalesBook getVbSalesBook() {
		return this.vbSalesBook;
	}

	public void setVbSalesBook(VbSalesBook vbSalesBook) {
		this.vbSalesBook = vbSalesBook;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getDayBookType() {
		return this.dayBookType;
	}

	public void setDayBookType(String dayBookType) {
		this.dayBookType = dayBookType;
	}

	public String getValueOne() {
		return this.valueOne;
	}

	public void setValueOne(String valueOne) {
		this.valueOne = valueOne;
	}

	public String getValueTwo() {
		return this.valueTwo;
	}

	public void setValueTwo(String valueTwo) {
		this.valueTwo = valueTwo;
	}

	public String getValueThree() {
		return this.valueThree;
	}

	public void setValueThree(String valueThree) {
		this.valueThree = valueThree;
	}

	public Set getVbCashDayBookCrs() {
		return this.vbCashDayBookCrs;
	}

	public void setVbCashDayBookCrs(Set vbCashDayBookCrs) {
		this.vbCashDayBookCrs = vbCashDayBookCrs;
	}

}
