package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VbCustomerAdvanceInfo generated by hbm2java
 */
public class VbCustomerAdvanceInfo implements java.io.Serializable {

	/**
	 * long variable holds serialVersionUID.
	 */
	private static final long serialVersionUID = -8474404483695119267L;
	private Integer id;
	private VbOrganization vbOrganization;
	private String invoiceNo;
	private String businessName;
	private String creditFrom;
	private String debitTo;
	private float advance;
	private float balance;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;

	public VbCustomerAdvanceInfo() {
	}

	public VbCustomerAdvanceInfo(VbOrganization vbOrganization,
			String businessName, String creditFrom, float advance,
			float balance, Date modifiedOn) {
		this.vbOrganization = vbOrganization;
		this.businessName = businessName;
		this.creditFrom = creditFrom;
		this.advance = advance;
		this.balance = balance;
		this.modifiedOn = modifiedOn;
	}

	public VbCustomerAdvanceInfo(VbOrganization vbOrganization,
			String invoiceNo, String businessName, String creditFrom,
			String debitTo, float advance, float balance, Date createdOn,
			String createdBy, Date modifiedOn, String modifiedBy) {
		this.vbOrganization = vbOrganization;
		this.invoiceNo = invoiceNo;
		this.businessName = businessName;
		this.creditFrom = creditFrom;
		this.debitTo = debitTo;
		this.advance = advance;
		this.balance = balance;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public String getInvoiceNo() {
		return this.invoiceNo;
	}

	public void setInvoiceNo(String invoiceNo) {
		this.invoiceNo = invoiceNo;
	}

	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public String getCreditFrom() {
		return this.creditFrom;
	}

	public void setCreditFrom(String creditFrom) {
		this.creditFrom = creditFrom;
	}

	public String getDebitTo() {
		return this.debitTo;
	}

	public void setDebitTo(String debitTo) {
		this.debitTo = debitTo;
	}

	public float getAdvance() {
		return this.advance;
	}

	public void setAdvance(float advance) {
		this.advance = advance;
	}

	public float getBalance() {
		return this.balance;
	}

	public void setBalance(float balance) {
		this.balance = balance;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
