package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbDayBookVehicleDetails generated by hbm2java
 */
public class VbDayBookVehicleDetails implements java.io.Serializable {

	private Integer id;
	private VbDayBook vbDayBook;
	private String driverName;
	private String vehicleNo;
	private float startingReading;
	private float endingReading;
	private String vehicleDetailsRemarks;

	public VbDayBookVehicleDetails() {
	}

	public VbDayBookVehicleDetails(VbDayBook vbDayBook, String vehicleNo,
			float startingReading, float endingReading) {
		this.vbDayBook = vbDayBook;
		this.vehicleNo = vehicleNo;
		this.startingReading = startingReading;
		this.endingReading = endingReading;
	}

	public VbDayBookVehicleDetails(VbDayBook vbDayBook, String driverName,
			String vehicleNo, float startingReading, float endingReading,
			String vehicleDetailsRemarks) {
		this.vbDayBook = vbDayBook;
		this.driverName = driverName;
		this.vehicleNo = vehicleNo;
		this.startingReading = startingReading;
		this.endingReading = endingReading;
		this.vehicleDetailsRemarks = vehicleDetailsRemarks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbDayBook getVbDayBook() {
		return this.vbDayBook;
	}

	public void setVbDayBook(VbDayBook vbDayBook) {
		this.vbDayBook = vbDayBook;
	}

	public String getDriverName() {
		return this.driverName;
	}

	public void setDriverName(String driverName) {
		this.driverName = driverName;
	}

	public String getVehicleNo() {
		return this.vehicleNo;
	}

	public void setVehicleNo(String vehicleNo) {
		this.vehicleNo = vehicleNo;
	}

	public float getStartingReading() {
		return this.startingReading;
	}

	public void setStartingReading(float startingReading) {
		this.startingReading = startingReading;
	}

	public float getEndingReading() {
		return this.endingReading;
	}

	public void setEndingReading(float endingReading) {
		this.endingReading = endingReading;
	}

	public String getVehicleDetailsRemarks() {
		return this.vehicleDetailsRemarks;
	}

	public void setVehicleDetailsRemarks(String vehicleDetailsRemarks) {
		this.vehicleDetailsRemarks = vehicleDetailsRemarks;
	}

}
