package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbDeliveryNotePayments generated by hbm2java
 */
public class VbDeliveryNotePayments implements java.io.Serializable {

	private Integer id;
	private VbDeliveryNote vbDeliveryNote;
	private float presentPayable;
	private float previousCredit;
	private float presentAdvance;
	private float totalPayable;
	private float presentPayment;
	private float balance;
	private String paymentType;
	private String chequeNo;
	private String bankName;
	private String bankLocation;
	private String branchName;

	public VbDeliveryNotePayments() {
	}

	public VbDeliveryNotePayments(VbDeliveryNote vbDeliveryNote,
			float presentPayable, float previousCredit, float presentAdvance,
			float totalPayable, float presentPayment, float balance,
			String paymentType) {
		this.vbDeliveryNote = vbDeliveryNote;
		this.presentPayable = presentPayable;
		this.previousCredit = previousCredit;
		this.presentAdvance = presentAdvance;
		this.totalPayable = totalPayable;
		this.presentPayment = presentPayment;
		this.balance = balance;
		this.paymentType = paymentType;
	}

	public VbDeliveryNotePayments(VbDeliveryNote vbDeliveryNote,
			float presentPayable, float previousCredit, float presentAdvance,
			float totalPayable, float presentPayment, float balance,
			String paymentType, String chequeNo, String bankName,
			String bankLocation, String branchName) {
		this.vbDeliveryNote = vbDeliveryNote;
		this.presentPayable = presentPayable;
		this.previousCredit = previousCredit;
		this.presentAdvance = presentAdvance;
		this.totalPayable = totalPayable;
		this.presentPayment = presentPayment;
		this.balance = balance;
		this.paymentType = paymentType;
		this.chequeNo = chequeNo;
		this.bankName = bankName;
		this.bankLocation = bankLocation;
		this.branchName = branchName;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbDeliveryNote getVbDeliveryNote() {
		return this.vbDeliveryNote;
	}

	public void setVbDeliveryNote(VbDeliveryNote vbDeliveryNote) {
		this.vbDeliveryNote = vbDeliveryNote;
	}

	public float getPresentPayable() {
		return this.presentPayable;
	}

	public void setPresentPayable(float presentPayable) {
		this.presentPayable = presentPayable;
	}

	public float getPreviousCredit() {
		return this.previousCredit;
	}

	public void setPreviousCredit(float previousCredit) {
		this.previousCredit = previousCredit;
	}

	public float getPresentAdvance() {
		return this.presentAdvance;
	}

	public void setPresentAdvance(float presentAdvance) {
		this.presentAdvance = presentAdvance;
	}

	public float getTotalPayable() {
		return this.totalPayable;
	}

	public void setTotalPayable(float totalPayable) {
		this.totalPayable = totalPayable;
	}

	public float getPresentPayment() {
		return this.presentPayment;
	}

	public void setPresentPayment(float presentPayment) {
		this.presentPayment = presentPayment;
	}

	public float getBalance() {
		return this.balance;
	}

	public void setBalance(float balance) {
		this.balance = balance;
	}

	public String getPaymentType() {
		return this.paymentType;
	}

	public void setPaymentType(String paymentType) {
		this.paymentType = paymentType;
	}

	public String getChequeNo() {
		return this.chequeNo;
	}

	public void setChequeNo(String chequeNo) {
		this.chequeNo = chequeNo;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getBankLocation() {
		return this.bankLocation;
	}

	public void setBankLocation(String bankLocation) {
		this.bankLocation = bankLocation;
	}

	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

}
