package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbDeliveryNoteProducts generated by hbm2java
 */
public class VbDeliveryNoteProducts implements java.io.Serializable {

	/**
	 * long variable holds serialVersionUID.
	 */
	private static final long serialVersionUID = -8751733827668314529L;
	private Integer id;
	private VbDeliveryNote vbDeliveryNote;
	private String productName;
	private String batchNumber;
	private int productQty;
	private Integer bonusQty;
	private String bonusReason;
	private float productCost;
	private float totalCost;

	public VbDeliveryNoteProducts() {
	}

	public VbDeliveryNoteProducts(VbDeliveryNote vbDeliveryNote,
			String productName, String batchNumber, int productQty,
			float productCost, float totalCost) {
		this.vbDeliveryNote = vbDeliveryNote;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.productQty = productQty;
		this.productCost = productCost;
		this.totalCost = totalCost;
	}

	public VbDeliveryNoteProducts(VbDeliveryNote vbDeliveryNote,
			String productName, String batchNumber, int productQty,
			Integer bonusQty, String bonusReason, float productCost,
			float totalCost) {
		this.vbDeliveryNote = vbDeliveryNote;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.productQty = productQty;
		this.bonusQty = bonusQty;
		this.bonusReason = bonusReason;
		this.productCost = productCost;
		this.totalCost = totalCost;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbDeliveryNote getVbDeliveryNote() {
		return this.vbDeliveryNote;
	}

	public void setVbDeliveryNote(VbDeliveryNote vbDeliveryNote) {
		this.vbDeliveryNote = vbDeliveryNote;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getBatchNumber() {
		return this.batchNumber;
	}

	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber;
	}

	public int getProductQty() {
		return this.productQty;
	}

	public void setProductQty(int productQty) {
		this.productQty = productQty;
	}

	public Integer getBonusQty() {
		return this.bonusQty;
	}

	public void setBonusQty(Integer bonusQty) {
		this.bonusQty = bonusQty;
	}

	public String getBonusReason() {
		return this.bonusReason;
	}

	public void setBonusReason(String bonusReason) {
		this.bonusReason = bonusReason;
	}

	public float getProductCost() {
		return this.productCost;
	}

	public void setProductCost(float productCost) {
		this.productCost = productCost;
	}

	public float getTotalCost() {
		return this.totalCost;
	}

	public void setTotalCost(float totalCost) {
		this.totalCost = totalCost;
	}

}
