package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VbInsystemAlertNotifications generated by hbm2java
 */
public class VbInsystemAlertNotifications implements java.io.Serializable {

	/**
	 * long variable holds serialVersionUID.
	 */
	private static final long serialVersionUID = 401557388401030181L;
	private Integer id;
	private VbOrganization vbOrganization;
	private VbLogin vbLogin;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private String alertType;
	private String description;
	private int flag;

	public VbInsystemAlertNotifications() {
	}

	public VbInsystemAlertNotifications(VbOrganization vbOrganization,
			VbLogin vbLogin, Date modifiedOn, int flag) {
		this.vbOrganization = vbOrganization;
		this.vbLogin = vbLogin;
		this.modifiedOn = modifiedOn;
		this.flag = flag;
	}

	public VbInsystemAlertNotifications(VbOrganization vbOrganization,
			VbLogin vbLogin, Date createdOn, String createdBy, Date modifiedOn,
			String modifiedBy, String alertType, String description, int flag) {
		this.vbOrganization = vbOrganization;
		this.vbLogin = vbLogin;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.alertType = alertType;
		this.description = description;
		this.flag = flag;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public VbLogin getVbLogin() {
		return this.vbLogin;
	}

	public void setVbLogin(VbLogin vbLogin) {
		this.vbLogin = vbLogin;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getAlertType() {
		return this.alertType;
	}

	public void setAlertType(String alertType) {
		this.alertType = alertType;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getFlag() {
		return this.flag;
	}

	public void setFlag(int flag) {
		this.flag = flag;
	}

}
