package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VbLogin generated by hbm2java
 */
public class VbLogin implements java.io.Serializable {

	/**
	 * long variable holds serialVersionUID.
	 */
	private static final long serialVersionUID = 5329724483778043355L;
	private Integer id;
	private VbOrganization vbOrganization;
	private String username;
	private String password;
	private char enabled;
	private Character firstTime;
	private Integer wrongPasswordCount;
	private Set vbInsystemAlertNotificationses = new HashSet(0);
	private Set vbAuthorities = new HashSet(0);

	public VbLogin() {
	}

	public VbLogin(VbOrganization vbOrganization, String username,
			String password, char enabled) {
		this.vbOrganization = vbOrganization;
		this.username = username;
		this.password = password;
		this.enabled = enabled;
	}

	public VbLogin(VbOrganization vbOrganization, String username,
			String password, char enabled, Character firstTime,
			Integer wrongPasswordCount, Set vbInsystemAlertNotificationses,
			Set vbAuthorities) {
		this.vbOrganization = vbOrganization;
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.firstTime = firstTime;
		this.wrongPasswordCount = wrongPasswordCount;
		this.vbInsystemAlertNotificationses = vbInsystemAlertNotificationses;
		this.vbAuthorities = vbAuthorities;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public char getEnabled() {
		return this.enabled;
	}

	public void setEnabled(char enabled) {
		this.enabled = enabled;
	}

	public Character getFirstTime() {
		return this.firstTime;
	}

	public void setFirstTime(Character firstTime) {
		this.firstTime = firstTime;
	}

	public Integer getWrongPasswordCount() {
		return this.wrongPasswordCount;
	}

	public void setWrongPasswordCount(Integer wrongPasswordCount) {
		this.wrongPasswordCount = wrongPasswordCount;
	}

	public Set getVbInsystemAlertNotificationses() {
		return this.vbInsystemAlertNotificationses;
	}

	public void setVbInsystemAlertNotificationses(
			Set vbInsystemAlertNotificationses) {
		this.vbInsystemAlertNotificationses = vbInsystemAlertNotificationses;
	}

	public Set getVbAuthorities() {
		return this.vbAuthorities;
	}

	public void setVbAuthorities(Set vbAuthorities) {
		this.vbAuthorities = vbAuthorities;
	}

}
