package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VbOrganization generated by hbm2java
 */
public class VbOrganization implements java.io.Serializable {

	/**
	 * long variable holds serialVersionUID.
	 */
	private static final long serialVersionUID = 5033735680848903458L;
	private Integer id;
	private String superUserName;
	private String name;
	private String organizationCode;
	private String fullName;
	private String branchName;
	private String mainBranch;
	private String description;
	private String addressLine1;
	private String addressLine2;
	private String locality;
	private String landmark;
	private String city;
	private String state;
	private String country;
	private String currencyFormat;
	private String zipcode;
	private String phone1;
	private String phone2;
	private String mobile;
	private String alternateMobile;
	private String email;
	private String usernamePrefix;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private Set vbCustomerCreditInfos = new HashSet(0);
	private Set vbJournalTypeses = new HashSet(0);
	private Set vbLoginTracks = new HashSet(0);
	private Set vbDeliveryNotes = new HashSet(0);
	private Set vbCustomerChangeRequests = new HashSet(0);
	private Set vbEmployees = new HashSet(0);
	private Set vbSalesReturnChangeRequests = new HashSet(0);
	private Set vbDayBooks = new HashSet(0);
	private Set vbOrganizationMappingsForMainBranchId = new HashSet(0);
	private Set vbOrganizationMappingsForSubBranchId = new HashSet(0);
	private Set vbCustomerAdvanceInfos = new HashSet(0);
	private Set vbJournals = new HashSet(0);
	private Set vbLogins = new HashSet(0);
	private Set vbAssignOrganizationses = new HashSet(0);
	private Set vbSalesBooks = new HashSet(0);
	private Set vbUserDefinedAlertses = new HashSet(0);
	private Set vbInsystemAlertNotificationses = new HashSet(0);
	private Set vbCustomerDebitTransactions = new HashSet(0);
	private Set vbProductInventoryTransactions = new HashSet(0);
	private Set vbCashDayBookCrs = new HashSet(0);
	private Set vbDeliveryNoteChangeRequests = new HashSet(0);
	private Set vbSalesReturns = new HashSet(0);
	private Set vbSystemNotificationses = new HashSet(0);
	private Set vbDayBookChangeRequests = new HashSet(0);
	private Set vbCustomerCreditTransactions = new HashSet(0);
	private Set vbProducts = new HashSet(0);
	private Set vbAddressTypeses = new HashSet(0);
	private Set vbProductCustomerCosts = new HashSet(0);
	private Set vbCustomers = new HashSet(0);
	private Set vbInvoiceNoPeriods = new HashSet(0);
	private Set vbEmployeeCustomers = new HashSet(0);
	private Set vbJournalChangeRequests = new HashSet(0);
	private Set vbCashDayBooks = new HashSet(0);
	private Set vbSystemAlertses = new HashSet(0);
	private Set vbPaymentTypeses = new HashSet(0);

	public VbOrganization() {
	}

	public VbOrganization(String superUserName, String name,
			String organizationCode, String fullName, String branchName,
			String mainBranch, String addressLine1, String locality,
			String city, String state, String country, String currencyFormat,
			String zipcode, String email, Date modifiedOn) {
		this.superUserName = superUserName;
		this.name = name;
		this.organizationCode = organizationCode;
		this.fullName = fullName;
		this.branchName = branchName;
		this.mainBranch = mainBranch;
		this.addressLine1 = addressLine1;
		this.locality = locality;
		this.city = city;
		this.state = state;
		this.country = country;
		this.currencyFormat = currencyFormat;
		this.zipcode = zipcode;
		this.email = email;
		this.modifiedOn = modifiedOn;
	}

	public VbOrganization(String superUserName, String name,
			String organizationCode, String fullName, String branchName,
			String mainBranch, String description, String addressLine1,
			String addressLine2, String locality, String landmark, String city,
			String state, String country, String currencyFormat,
			String zipcode, String phone1, String phone2, String mobile,
			String alternateMobile, String usernamePrefix, String email, Date createdOn,
			String createdBy, Date modifiedOn, String modifiedBy,
			Set vbCustomerCreditInfos, Set vbJournalTypeses, Set vbLoginTracks,
			Set vbDeliveryNotes, Set vbCustomerChangeRequests, Set vbEmployees,
			Set vbSalesReturnChangeRequests, Set vbDayBooks,
			Set vbOrganizationMappingsForMainBranchId,
			Set vbOrganizationMappingsForSubBranchId,
			Set vbCustomerAdvanceInfos, Set vbJournals, Set vbLogins,
			Set vbAssignOrganizationses, Set vbSalesBooks,
			Set vbUserDefinedAlertses, Set vbInsystemAlertNotificationses,
			Set vbCustomerDebitTransactions,
			Set vbProductInventoryTransactions, Set vbCashDayBookCrs,
			Set vbDeliveryNoteChangeRequests, Set vbSalesReturns,
			Set vbSystemNotificationses, Set vbDayBookChangeRequests,
			Set vbCustomerCreditTransactions, Set vbProducts,
			Set vbAddressTypeses, Set vbProductCustomerCosts, Set vbCustomers,
			Set vbInvoiceNoPeriods, Set vbEmployeeCustomers,
			Set vbJournalChangeRequests, Set vbCashDayBooks,
			Set vbSystemAlertses, Set vbPaymentTypeses) {
		this.superUserName = superUserName;
		this.name = name;
		this.organizationCode = organizationCode;
		this.fullName = fullName;
		this.branchName = branchName;
		this.mainBranch = mainBranch;
		this.description = description;
		this.addressLine1 = addressLine1;
		this.addressLine2 = addressLine2;
		this.locality = locality;
		this.landmark = landmark;
		this.city = city;
		this.state = state;
		this.country = country;
		this.currencyFormat = currencyFormat;
		this.zipcode = zipcode;
		this.phone1 = phone1;
		this.phone2 = phone2;
		this.mobile = mobile;
		this.alternateMobile = alternateMobile;
		this.usernamePrefix = usernamePrefix;
		this.email = email;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.vbCustomerCreditInfos = vbCustomerCreditInfos;
		this.vbJournalTypeses = vbJournalTypeses;
		this.vbLoginTracks = vbLoginTracks;
		this.vbDeliveryNotes = vbDeliveryNotes;
		this.vbCustomerChangeRequests = vbCustomerChangeRequests;
		this.vbEmployees = vbEmployees;
		this.vbSalesReturnChangeRequests = vbSalesReturnChangeRequests;
		this.vbDayBooks = vbDayBooks;
		this.vbOrganizationMappingsForMainBranchId = vbOrganizationMappingsForMainBranchId;
		this.vbOrganizationMappingsForSubBranchId = vbOrganizationMappingsForSubBranchId;
		this.vbCustomerAdvanceInfos = vbCustomerAdvanceInfos;
		this.vbJournals = vbJournals;
		this.vbLogins = vbLogins;
		this.vbAssignOrganizationses = vbAssignOrganizationses;
		this.vbSalesBooks = vbSalesBooks;
		this.vbUserDefinedAlertses = vbUserDefinedAlertses;
		this.vbInsystemAlertNotificationses = vbInsystemAlertNotificationses;
		this.vbCustomerDebitTransactions = vbCustomerDebitTransactions;
		this.vbProductInventoryTransactions = vbProductInventoryTransactions;
		this.vbCashDayBookCrs = vbCashDayBookCrs;
		this.vbDeliveryNoteChangeRequests = vbDeliveryNoteChangeRequests;
		this.vbSalesReturns = vbSalesReturns;
		this.vbSystemNotificationses = vbSystemNotificationses;
		this.vbDayBookChangeRequests = vbDayBookChangeRequests;
		this.vbCustomerCreditTransactions = vbCustomerCreditTransactions;
		this.vbProducts = vbProducts;
		this.vbAddressTypeses = vbAddressTypeses;
		this.vbProductCustomerCosts = vbProductCustomerCosts;
		this.vbCustomers = vbCustomers;
		this.vbInvoiceNoPeriods = vbInvoiceNoPeriods;
		this.vbEmployeeCustomers = vbEmployeeCustomers;
		this.vbJournalChangeRequests = vbJournalChangeRequests;
		this.vbCashDayBooks = vbCashDayBooks;
		this.vbSystemAlertses = vbSystemAlertses;
		this.vbPaymentTypeses = vbPaymentTypeses;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getSuperUserName() {
		return this.superUserName;
	}

	public void setSuperUserName(String superUserName) {
		this.superUserName = superUserName;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getOrganizationCode() {
		return this.organizationCode;
	}

	public void setOrganizationCode(String organizationCode) {
		this.organizationCode = organizationCode;
	}

	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

	public String getBranchName() {
		return this.branchName;
	}

	public void setBranchName(String branchName) {
		this.branchName = branchName;
	}

	public String getMainBranch() {
		return this.mainBranch;
	}

	public void setMainBranch(String mainBranch) {
		this.mainBranch = mainBranch;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getAddressLine1() {
		return this.addressLine1;
	}

	public void setAddressLine1(String addressLine1) {
		this.addressLine1 = addressLine1;
	}

	public String getAddressLine2() {
		return this.addressLine2;
	}

	public void setAddressLine2(String addressLine2) {
		this.addressLine2 = addressLine2;
	}

	public String getLocality() {
		return this.locality;
	}

	public void setLocality(String locality) {
		this.locality = locality;
	}

	public String getLandmark() {
		return this.landmark;
	}

	public void setLandmark(String landmark) {
		this.landmark = landmark;
	}

	public String getCity() {
		return this.city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getState() {
		return this.state;
	}

	public void setState(String state) {
		this.state = state;
	}

	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	public String getCurrencyFormat() {
		return this.currencyFormat;
	}

	public void setCurrencyFormat(String currencyFormat) {
		this.currencyFormat = currencyFormat;
	}

	public String getZipcode() {
		return this.zipcode;
	}

	public void setZipcode(String zipcode) {
		this.zipcode = zipcode;
	}

	public String getPhone1() {
		return this.phone1;
	}

	public void setPhone1(String phone1) {
		this.phone1 = phone1;
	}

	public String getPhone2() {
		return this.phone2;
	}

	public void setPhone2(String phone2) {
		this.phone2 = phone2;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getAlternateMobile() {
		return this.alternateMobile;
	}

	public void setAlternateMobile(String alternateMobile) {
		this.alternateMobile = alternateMobile;
	}

	public String getUsernamePrefix() {
		return usernamePrefix;
	}

	public void setUsernamePrefix(String usernamePrefix) {
		this.usernamePrefix = usernamePrefix;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set getVbCustomerCreditInfos() {
		return this.vbCustomerCreditInfos;
	}

	public void setVbCustomerCreditInfos(Set vbCustomerCreditInfos) {
		this.vbCustomerCreditInfos = vbCustomerCreditInfos;
	}

	public Set getVbJournalTypeses() {
		return this.vbJournalTypeses;
	}

	public void setVbJournalTypeses(Set vbJournalTypeses) {
		this.vbJournalTypeses = vbJournalTypeses;
	}

	public Set getVbLoginTracks() {
		return this.vbLoginTracks;
	}

	public void setVbLoginTracks(Set vbLoginTracks) {
		this.vbLoginTracks = vbLoginTracks;
	}

	public Set getVbDeliveryNotes() {
		return this.vbDeliveryNotes;
	}

	public void setVbDeliveryNotes(Set vbDeliveryNotes) {
		this.vbDeliveryNotes = vbDeliveryNotes;
	}

	public Set getVbCustomerChangeRequests() {
		return this.vbCustomerChangeRequests;
	}

	public void setVbCustomerChangeRequests(Set vbCustomerChangeRequests) {
		this.vbCustomerChangeRequests = vbCustomerChangeRequests;
	}

	public Set getVbEmployees() {
		return this.vbEmployees;
	}

	public void setVbEmployees(Set vbEmployees) {
		this.vbEmployees = vbEmployees;
	}

	public Set getVbSalesReturnChangeRequests() {
		return this.vbSalesReturnChangeRequests;
	}

	public void setVbSalesReturnChangeRequests(Set vbSalesReturnChangeRequests) {
		this.vbSalesReturnChangeRequests = vbSalesReturnChangeRequests;
	}

	public Set getVbDayBooks() {
		return this.vbDayBooks;
	}

	public void setVbDayBooks(Set vbDayBooks) {
		this.vbDayBooks = vbDayBooks;
	}

	public Set getVbOrganizationMappingsForMainBranchId() {
		return this.vbOrganizationMappingsForMainBranchId;
	}

	public void setVbOrganizationMappingsForMainBranchId(
			Set vbOrganizationMappingsForMainBranchId) {
		this.vbOrganizationMappingsForMainBranchId = vbOrganizationMappingsForMainBranchId;
	}

	public Set getVbOrganizationMappingsForSubBranchId() {
		return this.vbOrganizationMappingsForSubBranchId;
	}

	public void setVbOrganizationMappingsForSubBranchId(
			Set vbOrganizationMappingsForSubBranchId) {
		this.vbOrganizationMappingsForSubBranchId = vbOrganizationMappingsForSubBranchId;
	}

	public Set getVbCustomerAdvanceInfos() {
		return this.vbCustomerAdvanceInfos;
	}

	public void setVbCustomerAdvanceInfos(Set vbCustomerAdvanceInfos) {
		this.vbCustomerAdvanceInfos = vbCustomerAdvanceInfos;
	}

	public Set getVbJournals() {
		return this.vbJournals;
	}

	public void setVbJournals(Set vbJournals) {
		this.vbJournals = vbJournals;
	}

	public Set getVbLogins() {
		return this.vbLogins;
	}

	public void setVbLogins(Set vbLogins) {
		this.vbLogins = vbLogins;
	}

	public Set getVbAssignOrganizationses() {
		return this.vbAssignOrganizationses;
	}

	public void setVbAssignOrganizationses(Set vbAssignOrganizationses) {
		this.vbAssignOrganizationses = vbAssignOrganizationses;
	}

	public Set getVbSalesBooks() {
		return this.vbSalesBooks;
	}

	public void setVbSalesBooks(Set vbSalesBooks) {
		this.vbSalesBooks = vbSalesBooks;
	}

	public Set getVbUserDefinedAlertses() {
		return this.vbUserDefinedAlertses;
	}

	public void setVbUserDefinedAlertses(Set vbUserDefinedAlertses) {
		this.vbUserDefinedAlertses = vbUserDefinedAlertses;
	}

	public Set getVbInsystemAlertNotificationses() {
		return this.vbInsystemAlertNotificationses;
	}

	public void setVbInsystemAlertNotificationses(
			Set vbInsystemAlertNotificationses) {
		this.vbInsystemAlertNotificationses = vbInsystemAlertNotificationses;
	}

	public Set getVbCustomerDebitTransactions() {
		return this.vbCustomerDebitTransactions;
	}

	public void setVbCustomerDebitTransactions(Set vbCustomerDebitTransactions) {
		this.vbCustomerDebitTransactions = vbCustomerDebitTransactions;
	}

	public Set getVbProductInventoryTransactions() {
		return this.vbProductInventoryTransactions;
	}

	public void setVbProductInventoryTransactions(
			Set vbProductInventoryTransactions) {
		this.vbProductInventoryTransactions = vbProductInventoryTransactions;
	}

	public Set getVbCashDayBookCrs() {
		return this.vbCashDayBookCrs;
	}

	public void setVbCashDayBookCrs(Set vbCashDayBookCrs) {
		this.vbCashDayBookCrs = vbCashDayBookCrs;
	}

	public Set getVbDeliveryNoteChangeRequests() {
		return this.vbDeliveryNoteChangeRequests;
	}

	public void setVbDeliveryNoteChangeRequests(Set vbDeliveryNoteChangeRequests) {
		this.vbDeliveryNoteChangeRequests = vbDeliveryNoteChangeRequests;
	}

	public Set getVbSalesReturns() {
		return this.vbSalesReturns;
	}

	public void setVbSalesReturns(Set vbSalesReturns) {
		this.vbSalesReturns = vbSalesReturns;
	}

	public Set getVbSystemNotificationses() {
		return this.vbSystemNotificationses;
	}

	public void setVbSystemNotificationses(Set vbSystemNotificationses) {
		this.vbSystemNotificationses = vbSystemNotificationses;
	}

	public Set getVbDayBookChangeRequests() {
		return this.vbDayBookChangeRequests;
	}

	public void setVbDayBookChangeRequests(Set vbDayBookChangeRequests) {
		this.vbDayBookChangeRequests = vbDayBookChangeRequests;
	}

	public Set getVbCustomerCreditTransactions() {
		return this.vbCustomerCreditTransactions;
	}

	public void setVbCustomerCreditTransactions(Set vbCustomerCreditTransactions) {
		this.vbCustomerCreditTransactions = vbCustomerCreditTransactions;
	}

	public Set getVbProducts() {
		return this.vbProducts;
	}

	public void setVbProducts(Set vbProducts) {
		this.vbProducts = vbProducts;
	}

	public Set getVbAddressTypeses() {
		return this.vbAddressTypeses;
	}

	public void setVbAddressTypeses(Set vbAddressTypeses) {
		this.vbAddressTypeses = vbAddressTypeses;
	}

	public Set getVbProductCustomerCosts() {
		return this.vbProductCustomerCosts;
	}

	public void setVbProductCustomerCosts(Set vbProductCustomerCosts) {
		this.vbProductCustomerCosts = vbProductCustomerCosts;
	}

	public Set getVbCustomers() {
		return this.vbCustomers;
	}

	public void setVbCustomers(Set vbCustomers) {
		this.vbCustomers = vbCustomers;
	}

	public Set getVbInvoiceNoPeriods() {
		return this.vbInvoiceNoPeriods;
	}

	public void setVbInvoiceNoPeriods(Set vbInvoiceNoPeriods) {
		this.vbInvoiceNoPeriods = vbInvoiceNoPeriods;
	}

	public Set getVbEmployeeCustomers() {
		return this.vbEmployeeCustomers;
	}

	public void setVbEmployeeCustomers(Set vbEmployeeCustomers) {
		this.vbEmployeeCustomers = vbEmployeeCustomers;
	}

	public Set getVbJournalChangeRequests() {
		return this.vbJournalChangeRequests;
	}

	public void setVbJournalChangeRequests(Set vbJournalChangeRequests) {
		this.vbJournalChangeRequests = vbJournalChangeRequests;
	}

	public Set getVbCashDayBooks() {
		return this.vbCashDayBooks;
	}

	public void setVbCashDayBooks(Set vbCashDayBooks) {
		this.vbCashDayBooks = vbCashDayBooks;
	}

	public Set getVbSystemAlertses() {
		return this.vbSystemAlertses;
	}

	public void setVbSystemAlertses(Set vbSystemAlertses) {
		this.vbSystemAlertses = vbSystemAlertses;
	}

	public Set getVbPaymentTypeses() {
		return this.vbPaymentTypeses;
	}

	public void setVbPaymentTypeses(Set vbPaymentTypeses) {
		this.vbPaymentTypeses = vbPaymentTypeses;
	}

}
