package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VbProductInventoryTransaction generated by hbm2java
 */
public class VbProductInventoryTransaction implements java.io.Serializable {

	private Integer id;
	private VbOrganization vbOrganization;
	private String productName;
	private String batchNumber;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private String salesExecutive;
	private Integer quantity;
	private String quantityType;

	public VbProductInventoryTransaction() {
	}

	public VbProductInventoryTransaction(VbOrganization vbOrganization,
			String productName, String batchNumber, Date modifiedOn) {
		this.vbOrganization = vbOrganization;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.modifiedOn = modifiedOn;
	}

	public VbProductInventoryTransaction(VbOrganization vbOrganization,
			String productName, String batchNumber, Date createdOn,
			String createdBy, Date modifiedOn, String modifiedBy,
			String salesExecutive, Integer quantity, String quantityType) {
		this.vbOrganization = vbOrganization;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.salesExecutive = salesExecutive;
		this.quantity = quantity;
		this.quantityType = quantityType;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getBatchNumber() {
		return this.batchNumber;
	}

	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getSalesExecutive() {
		return this.salesExecutive;
	}

	public void setSalesExecutive(String salesExecutive) {
		this.salesExecutive = salesExecutive;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public String getQuantityType() {
		return this.quantityType;
	}

	public void setQuantityType(String quantityType) {
		this.quantityType = quantityType;
	}

}
