package com.vekomy.vbooks.hibernate.model;

// Generated 29 Apr, 2014 5:00:18 PM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VbSalesBookAllotments generated by hbm2java
 */
public class VbSalesBookAllotments implements java.io.Serializable {

	private Integer id;
	private VbSalesBook vbSalesBook;
	private String productName;
	private String batchNumber;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private Integer qtyAllotted;
	private String remarks;

	public VbSalesBookAllotments() {
	}

	public VbSalesBookAllotments(VbSalesBook vbSalesBook, String productName,
			String batchNumber, Date modifiedOn) {
		this.vbSalesBook = vbSalesBook;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.modifiedOn = modifiedOn;
	}

	public VbSalesBookAllotments(int salesId, String productName,
			String batchNumber, Date createdOn, String createdBy,
			Date modifiedOn, String modifiedBy, Integer qtyAllotted,
			String remarks) {
		this.vbSalesBook = vbSalesBook;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.qtyAllotted = qtyAllotted;
		this.remarks = remarks;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbSalesBook getVbSalesBook() {
		return vbSalesBook;
	}

	public void setVbSalesBook(VbSalesBook vbSalesBook) {
		this.vbSalesBook = vbSalesBook;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getBatchNumber() {
		return this.batchNumber;
	}

	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Integer getQtyAllotted() {
		return this.qtyAllotted;
	}

	public void setQtyAllotted(Integer qtyAllotted) {
		this.qtyAllotted = qtyAllotted;
	}

	public String getRemarks() {
		return this.remarks;
	}

	public void setRemarks(String remarks) {
		this.remarks = remarks;
	}

}
