package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbSystemAlertsNotifications generated by hbm2java
 */
public class VbSystemAlertsNotifications implements java.io.Serializable {

	/**
	 * long variable holds serialVersionUID.
	 */
	private static final long serialVersionUID = -3439286985040154189L;
	private Integer id;
	private VbSystemAlerts vbSystemAlerts;
	private VbEmployee vbEmployee;
	private VbRole vbRole;
	private VbNotifications vbNotifications;
	private Boolean mailsTo;
	private Boolean mailsCc;
	private Boolean mailsBcc;

	public VbSystemAlertsNotifications() {
	}

	public VbSystemAlertsNotifications(VbSystemAlerts vbSystemAlerts,
			VbEmployee vbEmployee, VbRole vbRole,
			VbNotifications vbNotifications) {
		this.vbSystemAlerts = vbSystemAlerts;
		this.vbEmployee = vbEmployee;
		this.vbRole = vbRole;
		this.vbNotifications = vbNotifications;
	}

	public VbSystemAlertsNotifications(VbSystemAlerts vbSystemAlerts,
			VbEmployee vbEmployee, VbRole vbRole,
			VbNotifications vbNotifications, Boolean mailsTo, Boolean mailsCc,
			Boolean mailsBcc) {
		this.vbSystemAlerts = vbSystemAlerts;
		this.vbEmployee = vbEmployee;
		this.vbRole = vbRole;
		this.vbNotifications = vbNotifications;
		this.mailsTo = mailsTo;
		this.mailsCc = mailsCc;
		this.mailsBcc = mailsBcc;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbSystemAlerts getVbSystemAlerts() {
		return this.vbSystemAlerts;
	}

	public void setVbSystemAlerts(VbSystemAlerts vbSystemAlerts) {
		this.vbSystemAlerts = vbSystemAlerts;
	}

	public VbEmployee getVbEmployee() {
		return this.vbEmployee;
	}

	public void setVbEmployee(VbEmployee vbEmployee) {
		this.vbEmployee = vbEmployee;
	}

	public VbRole getVbRole() {
		return this.vbRole;
	}

	public void setVbRole(VbRole vbRole) {
		this.vbRole = vbRole;
	}

	public VbNotifications getVbNotifications() {
		return this.vbNotifications;
	}

	public void setVbNotifications(VbNotifications vbNotifications) {
		this.vbNotifications = vbNotifications;
	}

	public Boolean getMailsTo() {
		return this.mailsTo;
	}

	public void setMailsTo(Boolean mailsTo) {
		this.mailsTo = mailsTo;
	}

	public Boolean getMailsCc() {
		return this.mailsCc;
	}

	public void setMailsCc(Boolean mailsCc) {
		this.mailsCc = mailsCc;
	}

	public Boolean getMailsBcc() {
		return this.mailsBcc;
	}

	public void setMailsBcc(Boolean mailsBcc) {
		this.mailsBcc = mailsBcc;
	}

}
