package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VbSystemAlerts generated by hbm2java
 */
public class VbSystemAlerts implements java.io.Serializable {

	/**
	 * long variable holds serialVersionUID.
	 */
	private static final long serialVersionUID = -9160320589776284715L;
	private Integer id;
	private VbOrganization vbOrganization;
	private VbAlertType vbAlertType;
	private String alertName;
	private String description;
	private Boolean activeInactive;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private Set vbSystemAlertsNotificationses = new HashSet(0);
	private Set vbSystemAlertsHistories = new HashSet(0);

	public VbSystemAlerts() {
	}

	public VbSystemAlerts(VbAlertType vbAlertType, String alertName,
			Date modifiedOn) {
		this.vbAlertType = vbAlertType;
		this.alertName = alertName;
		this.modifiedOn = modifiedOn;
	}

	public VbSystemAlerts(VbOrganization vbOrganization,
			VbAlertType vbAlertType, String alertName, String description,
			Boolean activeInactive, Date createdOn, String createdBy,
			Date modifiedOn, String modifiedBy,
			Set vbSystemAlertsNotificationses, Set vbSystemAlertsHistories) {
		this.vbOrganization = vbOrganization;
		this.vbAlertType = vbAlertType;
		this.alertName = alertName;
		this.description = description;
		this.activeInactive = activeInactive;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.vbSystemAlertsNotificationses = vbSystemAlertsNotificationses;
		this.vbSystemAlertsHistories = vbSystemAlertsHistories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public VbAlertType getVbAlertType() {
		return this.vbAlertType;
	}

	public void setVbAlertType(VbAlertType vbAlertType) {
		this.vbAlertType = vbAlertType;
	}

	public String getAlertName() {
		return this.alertName;
	}

	public void setAlertName(String alertName) {
		this.alertName = alertName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Boolean getActiveInactive() {
		return this.activeInactive;
	}

	public void setActiveInactive(Boolean activeInactive) {
		this.activeInactive = activeInactive;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set getVbSystemAlertsNotificationses() {
		return this.vbSystemAlertsNotificationses;
	}

	public void setVbSystemAlertsNotificationses(
			Set vbSystemAlertsNotificationses) {
		this.vbSystemAlertsNotificationses = vbSystemAlertsNotificationses;
	}

	public Set getVbSystemAlertsHistories() {
		return this.vbSystemAlertsHistories;
	}

	public void setVbSystemAlertsHistories(Set vbSystemAlertsHistories) {
		this.vbSystemAlertsHistories = vbSystemAlertsHistories;
	}

}
