package com.vekomy.vbooks.app.hibernate.model;

// Generated Jul 4, 2013 9:22:12 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbAuthority generated by hbm2java
 */
public class VbAuthority implements java.io.Serializable {

	private Integer id;
	private VbRole vbRole;
	private VbLogin vbLogin;

	public VbAuthority() {
	}

	public VbAuthority(VbRole vbRole, VbLogin vbLogin) {
		this.vbRole = vbRole;
		this.vbLogin = vbLogin;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbRole getVbRole() {
		return this.vbRole;
	}

	public void setVbRole(VbRole vbRole) {
		this.vbRole = vbRole;
	}

	public VbLogin getVbLogin() {
		return this.vbLogin;
	}

	public void setVbLogin(VbLogin vbLogin) {
		this.vbLogin = vbLogin;
	}

}
