package com.vekomy.vbooks.app.hibernate.model;

// Generated Jul 4, 2013 9:22:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;

/**
 * VbCustomerCreditInfo generated by hbm2java
 */
public class VbCustomerCreditInfo implements java.io.Serializable {

	private Integer id;
	private VbOrganization vbOrganization;
	private String businessName;
	private String creditFrom;
	private String debitTo;
	private float balance;
	private Float due;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;

	public VbCustomerCreditInfo() {
	}

	public VbCustomerCreditInfo(VbOrganization vbOrganization,
			String businessName, String creditFrom, float balance,
			Date modifiedOn) {
		this.vbOrganization = vbOrganization;
		this.businessName = businessName;
		this.creditFrom = creditFrom;
		this.balance = balance;
		this.modifiedOn = modifiedOn;
	}

	public VbCustomerCreditInfo(VbOrganization vbOrganization,
			String businessName, String creditFrom, String debitTo,
			float balance, Float due, Date createdOn, String createdBy,
			Date modifiedOn, String modifiedBy) {
		this.vbOrganization = vbOrganization;
		this.businessName = businessName;
		this.creditFrom = creditFrom;
		this.debitTo = debitTo;
		this.balance = balance;
		this.due = due;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public String getBusinessName() {
		return this.businessName;
	}

	public void setBusinessName(String businessName) {
		this.businessName = businessName;
	}

	public String getCreditFrom() {
		return this.creditFrom;
	}

	public void setCreditFrom(String creditFrom) {
		this.creditFrom = creditFrom;
	}

	public String getDebitTo() {
		return this.debitTo;
	}

	public void setDebitTo(String debitTo) {
		this.debitTo = debitTo;
	}

	public float getBalance() {
		return this.balance;
	}

	public void setBalance(float balance) {
		this.balance = balance;
	}

	public Float getDue() {
		return this.due;
	}

	public void setDue(Float due) {
		this.due = due;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

}
