package com.vekomy.vbooks.app.hibernate.model;

// Generated Jul 4, 2013 9:22:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VbEmployee generated by hbm2java
 */
public class VbEmployee implements java.io.Serializable {

	private Integer id;
	private VbOrganization vbOrganization;
	private String username;
	private String firstName;
	private String middleName;
	private String lastName;
	private String employeeNumber;
	private String employeeType;
	private String employeeEmail;
	private Character gender;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private Set vbEmployeeAddresses = new HashSet(0);
	private Set vbEmployeeCustomers = new HashSet(0);
	private Set vbAssignOrganizationses = new HashSet(0);
	private Set vbEmployeeDetails = new HashSet(0);

	public VbEmployee() {
	}

	public VbEmployee(String username, String firstName, String lastName,
			String employeeType, String employeeEmail, Date modifiedOn) {
		this.username = username;
		this.firstName = firstName;
		this.lastName = lastName;
		this.employeeType = employeeType;
		this.employeeEmail = employeeEmail;
		this.modifiedOn = modifiedOn;
	}

	public VbEmployee(VbOrganization vbOrganization, String username,
			String firstName, String middleName, String lastName,
			String employeeNumber, String employeeType, String employeeEmail,
			Character gender, Date createdOn, String createdBy,
			Date modifiedOn, String modifiedBy, Set vbEmployeeAddresses,
			Set vbEmployeeCustomers, Set vbAssignOrganizationses,
			Set vbEmployeeDetails) {
		this.vbOrganization = vbOrganization;
		this.username = username;
		this.firstName = firstName;
		this.middleName = middleName;
		this.lastName = lastName;
		this.employeeNumber = employeeNumber;
		this.employeeType = employeeType;
		this.employeeEmail = employeeEmail;
		this.gender = gender;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.vbEmployeeAddresses = vbEmployeeAddresses;
		this.vbEmployeeCustomers = vbEmployeeCustomers;
		this.vbAssignOrganizationses = vbAssignOrganizationses;
		this.vbEmployeeDetails = vbEmployeeDetails;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getMiddleName() {
		return this.middleName;
	}

	public void setMiddleName(String middleName) {
		this.middleName = middleName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getEmployeeNumber() {
		return this.employeeNumber;
	}

	public void setEmployeeNumber(String employeeNumber) {
		this.employeeNumber = employeeNumber;
	}

	public String getEmployeeType() {
		return this.employeeType;
	}

	public void setEmployeeType(String employeeType) {
		this.employeeType = employeeType;
	}

	public String getEmployeeEmail() {
		return this.employeeEmail;
	}

	public void setEmployeeEmail(String employeeEmail) {
		this.employeeEmail = employeeEmail;
	}

	public Character getGender() {
		return this.gender;
	}

	public void setGender(Character gender) {
		this.gender = gender;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public Set getVbEmployeeAddresses() {
		return this.vbEmployeeAddresses;
	}

	public void setVbEmployeeAddresses(Set vbEmployeeAddresses) {
		this.vbEmployeeAddresses = vbEmployeeAddresses;
	}

	public Set getVbEmployeeCustomers() {
		return this.vbEmployeeCustomers;
	}

	public void setVbEmployeeCustomers(Set vbEmployeeCustomers) {
		this.vbEmployeeCustomers = vbEmployeeCustomers;
	}

	public Set getVbAssignOrganizationses() {
		return this.vbAssignOrganizationses;
	}

	public void setVbAssignOrganizationses(Set vbAssignOrganizationses) {
		this.vbAssignOrganizationses = vbAssignOrganizationses;
	}

	public Set getVbEmployeeDetails() {
		return this.vbEmployeeDetails;
	}

	public void setVbEmployeeDetails(Set vbEmployeeDetails) {
		this.vbEmployeeDetails = vbEmployeeDetails;
	}

}
