package com.vekomy.vbooks.app.hibernate.model;

// Generated Jul 4, 2013 9:22:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VbLogin generated by hbm2java
 */
public class VbLogin implements java.io.Serializable {

	private Integer id;
	private String username;
	private String password;
	private char enabled;
	private Character firstTime;
	private Set vbAuthorities = new HashSet(0);

	public VbLogin() {
	}

	public VbLogin(String username, String password, char enabled) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
	}

	public VbLogin(String username, String password, char enabled,
			Character firstTime, Set vbAuthorities) {
		this.username = username;
		this.password = password;
		this.enabled = enabled;
		this.firstTime = firstTime;
		this.vbAuthorities = vbAuthorities;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	public char getEnabled() {
		return this.enabled;
	}

	public void setEnabled(char enabled) {
		this.enabled = enabled;
	}

	public Character getFirstTime() {
		return this.firstTime;
	}

	public void setFirstTime(Character firstTime) {
		this.firstTime = firstTime;
	}

	public Set getVbAuthorities() {
		return this.vbAuthorities;
	}

	public void setVbAuthorities(Set vbAuthorities) {
		this.vbAuthorities = vbAuthorities;
	}

}
