package com.vekomy.vbooks.app.hibernate.model;

// Generated Jul 4, 2013 9:22:12 AM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

/**
 * VbRole generated by hbm2java
 */
public class VbRole implements java.io.Serializable {

	private Integer id;
	private String roleName;
	private String description;
	private Set vbAuthorities = new HashSet(0);

	public VbRole() {
	}

	public VbRole(String roleName) {
		this.roleName = roleName;
	}

	public VbRole(String roleName, String description, Set vbAuthorities) {
		this.roleName = roleName;
		this.description = description;
		this.vbAuthorities = vbAuthorities;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getVbAuthorities() {
		return this.vbAuthorities;
	}

	public void setVbAuthorities(Set vbAuthorities) {
		this.vbAuthorities = vbAuthorities;
	}

}
