package com.vekomy.vbooks.app.hibernate.model;

// Generated Jul 4, 2013 9:22:12 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbSalesReturnChangeRequestProducts generated by hbm2java
 */
public class VbSalesReturnChangeRequestProducts implements java.io.Serializable {

	private Integer id;
	private VbSalesReturnChangeRequest vbSalesReturnChangeRequest;
	private String productName;
	private String batchNumber;
	private String damaged;
	private String resalable;
	private String totalQty;
	private String cost;
	private String totalCost;

	public VbSalesReturnChangeRequestProducts() {
	}

	public VbSalesReturnChangeRequestProducts(
			VbSalesReturnChangeRequest vbSalesReturnChangeRequest,
			String productName, String batchNumber, String cost,
			String totalCost) {
		this.vbSalesReturnChangeRequest = vbSalesReturnChangeRequest;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.cost = cost;
		this.totalCost = totalCost;
	}

	public VbSalesReturnChangeRequestProducts(
			VbSalesReturnChangeRequest vbSalesReturnChangeRequest,
			String productName, String batchNumber, String damaged,
			String resalable, String totalQty, String cost, String totalCost) {
		this.vbSalesReturnChangeRequest = vbSalesReturnChangeRequest;
		this.productName = productName;
		this.batchNumber = batchNumber;
		this.damaged = damaged;
		this.resalable = resalable;
		this.totalQty = totalQty;
		this.cost = cost;
		this.totalCost = totalCost;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbSalesReturnChangeRequest getVbSalesReturnChangeRequest() {
		return this.vbSalesReturnChangeRequest;
	}

	public void setVbSalesReturnChangeRequest(
			VbSalesReturnChangeRequest vbSalesReturnChangeRequest) {
		this.vbSalesReturnChangeRequest = vbSalesReturnChangeRequest;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getBatchNumber() {
		return this.batchNumber;
	}

	public void setBatchNumber(String batchNumber) {
		this.batchNumber = batchNumber;
	}

	public String getDamaged() {
		return this.damaged;
	}

	public void setDamaged(String damaged) {
		this.damaged = damaged;
	}

	public String getResalable() {
		return this.resalable;
	}

	public void setResalable(String resalable) {
		this.resalable = resalable;
	}

	public String getTotalQty() {
		return this.totalQty;
	}

	public void setTotalQty(String totalQty) {
		this.totalQty = totalQty;
	}

	public String getCost() {
		return this.cost;
	}

	public void setCost(String cost) {
		this.cost = cost;
	}

	public String getTotalCost() {
		return this.totalCost;
	}

	public void setTotalCost(String totalCost) {
		this.totalCost = totalCost;
	}

}
