package com.vekomy.vbooks.app.hibernate.model;

// Generated Jul 4, 2013 9:22:12 AM by Hibernate Tools 3.4.0.CR1

/**
 * VbUserSetting generated by hbm2java
 */
public class VbUserSetting implements java.io.Serializable {

	private Integer id;
	private String username;
	private String theme;
	private String favorite;

	public VbUserSetting() {
	}

	public VbUserSetting(String username) {
		this.username = username;
	}

	public VbUserSetting(String username, String theme, String favorite) {
		this.username = username;
		this.theme = theme;
		this.favorite = favorite;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getTheme() {
		return this.theme;
	}

	public void setTheme(String theme) {
		this.theme = theme;
	}

	public String getFavorite() {
		return this.favorite;
	}

	public void setFavorite(String favorite) {
		this.favorite = favorite;
	}

}
