package com.vekomy.vbooks.hibernate.model;

// Generated Sep 11, 2013 11:07:56 AM by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * VbUserDefinedAlerts generated by hbm2java
 */
public class VbUserDefinedAlerts implements java.io.Serializable {

	private Integer id;
	private VbOrganization vbOrganization;
	private VbAlertType vbAlertType;
	private String alertName;
	private Boolean activeInactive;
	private Date createdOn;
	private String createdBy;
	private Date modifiedOn;
	private String modifiedBy;
	private String description;
	private Set vbMySaleses = new HashSet(0);
	private Set vbUserDefinedAlertsNotificationses = new HashSet(0);
	private Set vbTrendings = new HashSet(0);
	private Set vbExcessCashs = new HashSet(0);
	private Set vbUserDefinedAlertsHistories = new HashSet(0);

	public VbUserDefinedAlerts() {
	}

	public VbUserDefinedAlerts(VbAlertType vbAlertType, String alertName,
			Date modifiedOn) {
		this.vbAlertType = vbAlertType;
		this.alertName = alertName;
		this.modifiedOn = modifiedOn;
	}

	public VbUserDefinedAlerts(VbOrganization vbOrganization,
			VbAlertType vbAlertType, String alertName, Boolean activeInactive,
			Date createdOn, String createdBy, Date modifiedOn,
			String modifiedBy, String description, Set vbMySaleses,
			Set vbUserDefinedAlertsNotificationses, Set vbTrendings,
			Set vbExcessCashs, Set vbUserDefinedAlertsHistories) {
		this.vbOrganization = vbOrganization;
		this.vbAlertType = vbAlertType;
		this.alertName = alertName;
		this.activeInactive = activeInactive;
		this.createdOn = createdOn;
		this.createdBy = createdBy;
		this.modifiedOn = modifiedOn;
		this.modifiedBy = modifiedBy;
		this.description = description;
		this.vbMySaleses = vbMySaleses;
		this.vbUserDefinedAlertsNotificationses = vbUserDefinedAlertsNotificationses;
		this.vbTrendings = vbTrendings;
		this.vbExcessCashs = vbExcessCashs;
		this.vbUserDefinedAlertsHistories = vbUserDefinedAlertsHistories;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public VbOrganization getVbOrganization() {
		return this.vbOrganization;
	}

	public void setVbOrganization(VbOrganization vbOrganization) {
		this.vbOrganization = vbOrganization;
	}

	public VbAlertType getVbAlertType() {
		return this.vbAlertType;
	}

	public void setVbAlertType(VbAlertType vbAlertType) {
		this.vbAlertType = vbAlertType;
	}

	public String getAlertName() {
		return this.alertName;
	}

	public void setAlertName(String alertName) {
		this.alertName = alertName;
	}

	public Boolean getActiveInactive() {
		return this.activeInactive;
	}

	public void setActiveInactive(Boolean activeInactive) {
		this.activeInactive = activeInactive;
	}

	public Date getCreatedOn() {
		return this.createdOn;
	}

	public void setCreatedOn(Date createdOn) {
		this.createdOn = createdOn;
	}

	public String getCreatedBy() {
		return this.createdBy;
	}

	public void setCreatedBy(String createdBy) {
		this.createdBy = createdBy;
	}

	public Date getModifiedOn() {
		return this.modifiedOn;
	}

	public void setModifiedOn(Date modifiedOn) {
		this.modifiedOn = modifiedOn;
	}

	public String getModifiedBy() {
		return this.modifiedBy;
	}

	public void setModifiedBy(String modifiedBy) {
		this.modifiedBy = modifiedBy;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public Set getVbMySaleses() {
		return this.vbMySaleses;
	}

	public void setVbMySaleses(Set vbMySaleses) {
		this.vbMySaleses = vbMySaleses;
	}

	public Set getVbUserDefinedAlertsNotificationses() {
		return this.vbUserDefinedAlertsNotificationses;
	}

	public void setVbUserDefinedAlertsNotificationses(
			Set vbUserDefinedAlertsNotificationses) {
		this.vbUserDefinedAlertsNotificationses = vbUserDefinedAlertsNotificationses;
	}

	public Set getVbTrendings() {
		return this.vbTrendings;
	}

	public void setVbTrendings(Set vbTrendings) {
		this.vbTrendings = vbTrendings;
	}

	public Set getVbExcessCashs() {
		return this.vbExcessCashs;
	}

	public void setVbExcessCashs(Set vbExcessCashs) {
		this.vbExcessCashs = vbExcessCashs;
	}

	public Set getVbUserDefinedAlertsHistories() {
		return this.vbUserDefinedAlertsHistories;
	}

	public void setVbUserDefinedAlertsHistories(Set vbUserDefinedAlertsHistories) {
		this.vbUserDefinedAlertsHistories = vbUserDefinedAlertsHistories;
	}

}
